### ISSUE TITLE
BooleanField required argument is ignored

### ISSUE THREAD

**Issue by willkg** [encode/django-rest-framework#1004]
It looks like BooleanFields get a default of False and because of that they can't be required. So doing this has no effect:

```
foo = serializers.BooleanField(required=True)
```

I'm pretty sure the problem is this in `rest_framework/fields.py` BooleanField definition:

```
    # Note: we set default to `False` in order to fill in missing value not
    # supplied by html form.  TODO: Fix so that only html form input gets
    # this behavior.
    default = False
```

**Comment by QinMing** [comment]
I think this issue still exist. Here's my code. I'm using djangorestframework==3.4.6

### in models.py
x = models.BooleanField()

### in serializers.py
x = serializers.BooleanField(required=True)

### POST body (JSON)
{
    "y": "no x here"
}

### Then I got 500 error:
IntegrityError: (1048, "Column 'x' cannot be null")

### What I expect
should return an 400 error saying "x is required".

**Comment by xordoquy** [comment]
This is covered by a test so it'll likely be something on your side. A test case highlighting the issue will be required to go further.

**Comment by thakryptex** [comment]
I have this problem too. (DRF 3.7.3)
I use simple Serializer (not ModelSerializer), it takes only one parameter 'is_male', which is BooleanField(required=True).
I found that if I didn't pass any parameters to serializer, it passes validation (instead of raising exception) and returns 'is_male' = False.
Something implicit going on there, it shouldn't be this way.

**Comment by xordoquy** [comment]
As said in previous comment, it's already covered and working with a test case in DRF test suite. So either your code is doing something wrong either there's an issue in DRF. In the later case we'll need a test case we can reproduce to highlight the issue.

**Comment by thakryptex** [comment]
Do you need code example to reproduce it?

Ok. I'm writing a test for a view, that have to throw validation error (because 'is_male' argument is required).
`response = self.client.post(self.url(self.user.uid), {})`
as you can see, post data is empty.

In the view I do this:
```
request_serializer = ChangeUserGenderSerializer(data=request.POST)
request_serializer.is_valid(raise_exception=True)
```
so, request.POST is empty (I've this with debugger) and is_valid() have to throw an exception if something goes wrong.

My serializer is:
```
class ChangeUserGenderSerializer(serializers.Serializer):
    is_male = serializers.BooleanField(required=True)
```

Result you can see here:
<img width="1059" alt="2017-12-04 12 11 02" src="https://user-images.githubusercontent.com/12232787/33544643-9ec01032-d8ec-11e7-9cde-01b29a368a3e.png">
Somehow it validates and returns False.

If I made a mistake somewhere, please, tell me, but as I can see there is no mistakes in code.

**Comment by carltongibson** [comment]
OK, but I just tried this in the shell and I get the expected result: 

```
>>> from rest_framework import serializers
>>> class ChangeUserGenderSerializer(serializers.Serializer):
...         is_male = serializers.BooleanField(required=True)
...
>>> serializer = ChangeUserGenderSerializer(data={})
>>> serializer.is_valid()
False
```

So there must be something else going on. 

@thakryptex Can you add a test case to the test suite that recreates your issue? If we have a failing PR we can see exactly what's going on, and fix it.

**Comment by xordoquy** [comment]
My bet, it's because data are sent through forms and the outcome would be the one expected.
Which is also why I ask for a test case and not code sample. This helps understand the issue and where is may lay.

**Comment by thakryptex** [comment]
Wow. Actually, it's pretty confusing.
Look, if I pass request.POST (or request.data) I get is_valid = True.
But if I pass dict(request.POST), then is_valid = False.

<img width="1905" alt="2017-12-04 12 57 23" src="https://user-images.githubusercontent.com/12232787/33546687-ba789992-d8f2-11e7-97e7-7219d9466330.png">

**Comment by xordoquy** [comment]
@thakryptex yes it is because it's forms and it's a usage question.
TL:DR you're using forms and all that behavior is expected. There's more about it in the Django documentation for `BooleanField`.
Now let's not turn this issue into a debug session please.

**Comment by thakryptex** [comment]
Ok, let's read: [Forms BooleanField](https://docs.djangoproject.com/en/1.11/ref/forms/fields/#booleanfield)
What we see there:
```
Empty value: False
Validates that the value is True (e.g. the check box is checked) if the field has required=True.
```
So, everything is fine and looks like it supposed to be. (I also checked BooleanField in Models)
But there is no answer on described problem.
Why with request.POST it always valid, but only with dict() it works properly?
