### ISSUE TITLE
Browsable API should support free-text input for the content type.

### ISSUE THREAD

**Issue by ptgolden** [encode/django-rest-framework#1579]
Attempting to construct a multipart/form-data request from the "Raw data" panel within the browseable API returns a 400. This is because django's MultiPartParser is never passed a value for the request's multi-part boundary. The error message is: "Multipart form parse error - Invalid boundary in multipart: None"

Would it make sense to have a default boundary?

**Comment by xordoquy** [comment]
As a starting point here we could have a failing test case if that happens with the APIClient.

**Comment by tomchristie** [comment]
I'm not sure what behavior we'd be looking from for any test case? What we provide is kind of valid, it's just that the browsable API UI could be more helpful to the user.

**Comment by levic** [comment]
https://github.com/encode/django-rest-framework/issues/1579

@tomchristie:
> What we provide is kind of valid

As far as I can determine, it is never valid.

## No Boundary Option in Content Type

Selecting "Media type: multipart/form-data" in the API browser will submit a header line of

`Content-Type: multipart/form-data`

When the request is parsed in [`MultiPartParser`](https://github.com/encode/django-rest-framework/blob/3.6.3/rest_framework/parsers.py#L87) it hands off to django's [`MultiPartParser`](https://github.com/django/django/blob/1.11.1/django/http/multipartparser.py#L48) which then [raises an exception](https://github.com/django/django/blob/1.11.1/django/http/multipartparser.py#L78) because there is no `boundary` parameter specified.

You can run a test using your browser's dev tools to modify the Media type dropdown (curiously the JS uses the option text, not the option value) and trick it into submitting a `multipart/form-data; boundary=foobar` content type header.

## Invalid EOL Char

Once you get past that hurdle, you run into [rfc2046](https://tools.ietf.org/html/rfc2046#section-5.1.1) used by [rfc7578](https://tools.ietf.org/html/rfc7578#section-4):
> The boundary delimiter line is then defined as a line ... whitespace, and *a terminating CRLF*.

According to the HTML5 spec though, the [API value](https://dev.w3.org/html5/spec-preview/the-textarea-element.html#concept-textarea-api-value) is normalised to remove all `\r` chars. 

When [`ajax-form.js`](https://github.com/encode/django-rest-framework/blob/3.6.3/rest_framework/static/rest_framework/js/ajax-form.js) fetches the submission content, [it uses](https://github.com/encode/django-rest-framework/blob/3.6.3/rest_framework/static/rest_framework/js/ajax-form.js#L39) the underlying html `value` which has been normalised. Django's form field [boundary detector](https://github.com/django/django/blob/1.11.1/django/http/multipartparser.py#L478) correctly detects the boundary, but [`parse_boundary_stream`](https://github.com/django/django/blob/1.11.1/django/http/multipartparser.py#L586) is not tolerant of LF-only EOL chars causing [`MultiPartParser`](https://github.com/django/django/blob/1.11.1/django/http/multipartparser.py#L48) to [ignore](https://github.com/django/django/blob/1.11.1/django/http/multipartparser.py#L168) each chunk. So your request makes it into your view, but has no data.

## Solution?
At least for me, this comes up because I cut & paste the body from a browser dev tools window to play around with it. Rather than changing the dropdown into a freeform text area, this just examines the content and appends the first valid boundary to the content type. (Strictly speaking someone _could_ put valid-looking boundary lines before the actual boundary but to handle this you'd basically have to attempt to fully parse the body using every potentially valid boundary and even then it might still be ambiguous)

It also doesn't handle the case where you might want the value of field(s) to contain only `\n` or `\r` but the html `textarea` has already mangled your data so there's nothing we can do about that -- it's at least an improvement on the current situation where no submissions will work.

As far as I can see there should be no side effects (not 100% on this though); is purely a JS-based fix so no test cases (unless I missed where they are)

The regex is based on the grammar at the end of [rfc2046](https://tools.ietf.org/html/rfc2046#page-43) but is a little stricter, allows whitespace but otherwise ignores the `An exact match of the entire candidate line is not required` requirement of [s5.1.1](https://tools.ietf.org/html/rfc2046#section-5.1.1) -- again, to fix that you'd have to fully parse the body using every possible candidate boundary.

**Comment by tomchristie** [comment]
> As far as I can determine, it is never valid.

For multipart, no. For everything else, yes.
