### ISSUE TITLE
Partial update skip required field validation

### ISSUE THREAD

**Issue by Geniushjs** [encode/django-rest-framework#1725]
It's caused by:

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L178-L179

I am not sure why the author need to set required=False then doing partial update?

**Comment by dmk23** [comment]
So what is the proper way to do this in 3.0?

**Comment by tomchristie** [comment]
@dmk23 - Looking through the thread it's not clear enough what the question is, or *if* there's any remaining issue. I'd suggest you start out asking your question on the discussion group, and consider moving it over here if you believe that it's an actionable bug.

**Comment by dmk23** [comment]
Never mind - solved the issue by selectively applying `required=False`, fully disabling validators on certain fields with `validators=[]` and replacing them with our custom validation logic ...

**Comment by simone6021** [comment]
Hello, first thanks for this great piece code.

I am re-opening this issue because it still seems like a bug to me even in version 3.x.
If a partial update is performed and a field marked as required is passed with a an empty value (even null if allow_null is set to true) the validation passes.

In my humble opinion, required fields should be checked and validated as such even in partial update, if they are passed in the payload.
