### ISSUE TITLE
Allow non-request-based transformation of relative to absolute URL for Hyperlinked*

### ISSUE THREAD

**Issue by carljm** [encode/django-rest-framework#1947]
Context for this feature request:
1. Generally in my projects, I don't want to pass a full request object everywhere I might need to generate full absolute URLs (including e.g. in emails generated by a Celery task that don't even have a request available). Therefore, I almost always have a `BASE_URL` setting that I use for this purpose, rather than `request.build_absolute_uri(...)`. Presuming I'm not trying to do dynamic domain-based multitenancy (and I rarely am), changing one setting per-deployment is much easier than passing a request to all kinds of places it doesn't belong.
2. I frequently use my DRF serializers outside the API framework. For example, I share templates between client and server (using Jinja2/nunjucks) and pre-render on the server the same template that may also be rendered on the client using data from the API, so I use the DRF serializer for the data passed in to the template on the server side, so it always gets the same data in the same format. When using a HyperlinkedModelSerializer outside the API, it's a pain to have to always pass in a request just so that it can generate absolute URLs.

Thus, I'd like to be able to customize how HyperlinkedModelSerializer/HyperlinkedRelatedField/HyperlinkedIdentityField build full absolute URLs, so that I can build them using my `BASE_URL` setting instead of using `request.build_absolute_uri(...)`, and remove their dependency on having a request in the context. Right now doing this requires overriding most of their implementation.

The implementation I'd suggest is to accept a `base_url`attribute on a HyperlinkedModelSerializer; if it's present, use it and don't look for or require a request in the context.

I will implement this and submit a PR if the idea/API are accepted in principle.

**Comment by swiharta** [comment]
Googling for how to use relative URLs instead of absolute URLs led me here. One reason is I want to minimize the size of my JSON, and including all the characters of many absolute URLs adds up to quite a large chunk of the total data in my case. I also add `'URL_FORMAT_OVERRIDE': None,` to my settings to drop the `&format=json` from every single generated URL, further decreasing the payload.

You can set `context={'request': None}` when instantiating a HyperlinkedModelSerializer in Django views, which seems to be the (undocumented?) official way to force using relative URLs (see `if request:` in the `_reverse()` method in reverse.py). So, you just have to make `request=None` when it gets to that `_reverse` method to also force DRF to use relative URLs for other API calls from a webapp.

Hopefully to help someone else, I take it overriding the `get_url` method for HyperlinkedRelatedField and subclassing as shown below is currently the best way to force relative URLs without editing the source code. It seems like there should be a simple setting for this that would be much more straightforward, and I've seen this proposal discussed elsewhere. +1 from me for doing that!

```python
class MyHyperlinkedRelatedField(relations.HyperlinkedRelatedField):
  def get_url(self, obj, view_name, request, format):
    request = None # force DRF to use relative URLs by setting request to None
    return super(MyHyperlinkedRelatedField, self).get_url(obj, view_name, request, format)

class MyHyperlinkedIdentityField(MyHyperlinkedRelatedField, relations.HyperlinkedIdentityField):
  pass

class MyHyperlinkedModelSerializer(serializers.HyperlinkedModelSerializer):
  serializer_related_field = MyHyperlinkedRelatedField
  serializer_url_field = MyHyperlinkedIdentityField
```
