### ISSUE TITLE
Ability to change depth value based on request type.

### ISSUE THREAD

**Issue by felixcheruiyot** [encode/django-rest-framework#1951]
With reference to [this](http://stackoverflow.com/questions/15883678/django-rest-framework-different-depth-for-post-put) query, I think it a widely requested feature. 

I agree you can use the pk and maybe the hyperlink serializer , but having nested related models in request will be awesome and you can choose to override this behaviour based on request type i.e POST, PUT or GET.

Consider this:
- Have all POST & PUT requests activate depth = 1
- GET to set depth more that 1
- Have a default to 0 if this override is not used.

Having flexibility and code reuse in serializers worths weight in gold.

**Comment by aidanlister** [comment]
Is it possible to initialise the serializer differently? I'm getting to this awkward point where I have six or seven serializers for a resource, because sometimes I need it to be lean and fast and sometimes I need lots of extra information.

In get_serializer_class in my ViewSet it would be cool if I can return FooSerializer(depth=self.request.GET.get('depth', 0)) or similar.
