### ISSUE TITLE
Automatically determine `select_related` and `prefetch_related` on ModelSerializer.

### ISSUE THREAD

**Issue by cancan101** [encode/django-rest-framework#1964]
I have a serializer that looks the the following:

``` python
class ReportSerializer(serializers.ModelSerializer):
    person = serializers.SlugRelatedField(slug_field='uuid')
```

which is causing an [N +1 select issue](http://stackoverflow.com/questions/97197/what-is-the-n1-selects-issue) because `select_related` is not being used to pre-query the `Person` object. This means that in order to serialize the person field when serializing a `Report`, each `Person` must be queried for its `uuid`.

We likely want to use `select_related` on all `SlugRelatedField` and likely all nested serializers somewhere like here: https://github.com/tomchristie/django-rest-framework/blob/e437520217e20d500d641b95482d49484b1f24a7/rest_framework/serializers.py#L570

**Comment by Deepakdubey90** [comment]
Hi,
i'm trying to query  with generic relation what should i use, either 'Select_related' or 'Prefetch_related'.
i'm having to two table user and contact. 
i'm using contact table as generic(created generic relation from django view) .
so i'm making query like: 
result = User.objects.filter().select_related('id')
in above queryset i'm passing "ID" to select_related . (ID is pk of "user" table and acting as Entity_object_id in "contact" table and Entity_content_type_id)
How can i get each user details with their contact details 
for generic relation  used link :https://docs.djangoproject.com/en/1.7/ref/contrib/contenttypes/#generic-relations.

**Comment by xordoquy** [comment]
@Deepakdubey90 please do use the mailing list, IRC or stack overflow for usage question.

**Comment by Deepakdubey90** [comment]
ok

**Comment by GeeWee** [comment]
I'm working on this over at [django-auto-prefetching](https://github.com/GeeWee/django-auto-prefetching)

I'm not quite ready to publish to PyPi yet, but so far I have an algorithm that passes tests for all the relationships(fk, m2m, 1to1)
It recursively scans the fields of the serializer, fetching nested relations if needed.

If anyone wants to try it out before I'm done publishing (maybe find out where it doesn't work and submit an issue to the repo?) I'm sharing the first version of the code here:
https://gist.github.com/GeeWee/5f82fd11d5e9c95bfe61993c07624ccc

**Comment by GeeWee** [comment]
First usable version of [django-auto-prefetching](https://itnext.io/optimizing-django-rest-framework-performance-with-django-auto-prefetching-c70ce316463e#3ec0-675cbb3a573b) is now live if anyone still has this problem

**Comment by thetarby** [comment]
Hello everyone,

We faced the same issues in some projects and I have created a simple package to use in our projects. Then I have decided to publish it in github and pypi for anyone who is interested. Btw it is still being tested and there might be bugs. You can check it out on https://github.com/thetarby/django-auto-related

**Simply what it does:** 

What django-rest gives us is the ability to know what will be accessed from the object before it is accessed by inspecting the source attribute of the fields defined in a serializer. 

Then it traces those sources back on django fields instances and translates them to `select_related`, `prefetch_related` and `only` methods of django. Note that it does not use django-rest fields to decide what to prefetch but django fields because what django-rest says a related_field may not be a related field for the django or vice versa. 

For instance, `serializers.CharField(source=related_model.title)` is not a related field for djangorest but in reality related_model should be prefetched to avoid n+1 problems. 

If you have any feedback I would be glad to hear from you on github.

**Comment by ramwin** [comment]
> First usable version of [django-auto-prefetching](https://itnext.io/optimizing-django-rest-framework-performance-with-django-auto-prefetching-c70ce316463e#3ec0-675cbb3a573b) is now live if anyone still has this problem

I'm using django-auto-prefeching in my company's project. It helps a lot. Thank you.

**Comment by GeeWee** [comment]
You're very welcome!
