### ISSUE TITLE
Consider `ValidationError` handling during save.

### ISSUE THREAD

**Issue by brianmay** [encode/django-rest-framework#2145]
Hello,

Previously, in DRF 2.x ValidationError were caught and turned into HTTP 400 errors.

However this doesn't seem to be happening any more in version 3.x. ValidationErrors are not caught and become HTTP 500 errors. This seems wrong.

I am not sure where ValidationError are meant to be caught. However I note that the create() method in CreateModelMixen calls is_valid() with raise_exception=True, and UpdateModelMixin has a similar update() method; yet neither method tries to catch the exception.

Also wondering where it is ok to raise ValidationError. Am am assuming that serializer.run_validators and serializer.validate() can raise ValidationError, but not so sure about seralizer.create() and seralizer.update() - it could be argued that any ValidationError need to be raised before this point.

Thanks

**Comment by mlorant** [comment]
I'm sorry to re-open this issue but I guess it needs clarification, since I did not find the information everywhere else.

How can we make something DRY with this behaviour? For example, I want to validate two fields together for any reason, let's say I want `self.x < self.y`. The first thought I had is to put this in the `MyModel.clean()` method:

    def clean(self):
        if self.x > self.y:
            raise ValidationError({'x': _(u"`x` should be less than `y`!")})

As said before, this won't be catched properly by DRF and leaves a 500 exception returns... I don't really want to copy/paste my validations at two places (the example is pretty simple, but we could image 10+ validations steps). How should we handle the exception, knowing the model is used outside DRF too?

**Comment by tomchristie** [comment]
I'd generally recommend having user facing validation errors strictly outside of model code (eg always enforce user input using serializers). However if you do need to do this I'd probably suggest providing a serializer `.validate()` method that instantiates the model and calls `.clean()`

**Comment by mlorant** [comment]
I'll consider this. After posting my comment, I thought of the logic behind this: it is indeed awkward to raises a 400 BAD REQUEST if the error comes from Django or the database level or any OS failure (even though we could only catch `ValidationError` and not `Exception`)... Explicit is better than implicit to counter this, as the Zen of Python said anyway.

**Comment by tomchristie** [comment]
> it is indeed awkward to raises a 400 BAD REQUEST if the error comes from Django or the database level or any OS failure 

Exactly so. Appreciate that this doesn't always sit cleanly with Django's model `.clean()` style, especially if both forms and serilalizers are being used, but I think that overall it's absolutely the best decision for our project.

**Comment by gabn88** [comment]
Hi guys, 

Very interesting topic indeed. I still find errors and validation one of the hardest topics, as it should always be done, and i find that the user should know what is going wrong! 

I'm having the same issues now. Multiple models with 10+ validation steps which are consumed both by the rest api and by regular views. I have read your comments, but could not understand what is the way to go now. Before I simple raised serializers.ValidationError() and everything was fine for my forms, but somehow things started breaking not since one of the latests updates (3.2.1 to 3.3.2 or so). Could one of you maybe post a practical example of how to do this? This would really help me a lot.

Thanks in advance!

**Comment by blazdivjak** [comment]
I tried solving it in the following way:

class ExampleViewSet(DefaultsMixin, LoggingMixin, viewsets.ModelViewSet):

    queryset = Example(active=True)
    filter_class = ExampleFilter
    serializer_class = ExampleSerializer

    def perform_update(self, serializer):

        try:
            instance = serializer.save()

        except Exception as detail:
            msg = "%s" % detail
            raise ValidationError(msg)

    def perform_create(self, serializer):

        try:
            instance = serializer.save()

        except Exception as detail:
            msg = "%s" % detail
            raise ValidationError(msg)

    def perform_destroy(self, instance):

        instance.delete()

**Comment by cnobile2012** [comment]
I've done pretty much the same thing as gabn88, though I feel this is less than an optimal solution and a bit kludgy. There really needs to be a DRF native way to execute model validators even if it needs to be switched on in the settings or something. The way it is now forces developers to break the DRY principle.

**Comment by xordoquy** [comment]
I'd second @blazdivjak solution with calling the object's clean and with more specific exceptions being caught. It keeps things dry and simple enough.

**Comment by gabn88** [comment]
Please don't use @blazdivjak 's solution this way. Then at least do something like this:

class ExampleViewSet(DefaultsMixin, LoggingMixin, viewsets.ModelViewSet):

    queryset = Example(active=True)
    filter_class = ExampleFilter
    serializer_class = ExampleSerializer

    def perform_update(self, serializer):

        try:
            instance = serializer.save()

        except django.core.exceptions.ValidationError as detail:
            msg = "%s" % detail
            raise serializers.ValidationError(msg)

    def perform_create(self, serializer):

        try:
            instance = serializer.save()

        except django.core.exceptions.ValidationError as detail:
            msg = "%s" % detail
            raise serializers.ValidationError(msg)

    def perform_destroy(self, instance):

        instance.delete()

Otherwise the users will also be informed of other exceptions which they probably don't want, and which you probably ought to get as a developer.

**Comment by cnobile2012** [comment]
Am I missing something here?

How does @blazdivjak 's method call the `instance.clean()`? I see no code that calls the clean method at all, The `serializer.save()` won't do this since this is the issue to begin with, the serializer doesn't call the models validators.

So please explain how this is supposed to work?

**Comment by xordoquy** [comment]
@cnobile2012 you get the overall idea. Implementation details are left to the developers since your mileage may vary. Want to clean the instance ? call it before saving the object then.

**Comment by cnobile2012** [comment]
Okay, I figured out what is happening here. @blazdivjak 's code works just
fine as is, but only if you are executing the `fullclean()` on the instance
when you save the model. This is what I was doing through a Mixin at the
end of the MRO. My unittests were screwed up and were failing till I fixed
them. After fixed everything worked as expected.

So the takeaway here is that one needs to be sure they are calling the
models validation when the model is saved and @blazdivjak 's code works
fine as is. If you are not calling `fullclean()` when the model is save I'd
suggest you do, but if you can't for some reason you will need to get the
instance before you call save on the serializer and call `clean()` on the
model instance.

On Fri, Dec 4, 2015 at 4:18 AM, Xavier Ordoquy <notifications@github.com>
wrote:

> @cnobile2012 <https://github.com/cnobile2012> you get the overall idea.
> Implementation details are left to the developers since your mileage may
> vary. Want to clean the instance ? call it before saving the object then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomchristie/django-rest-framework/issues/2145#issuecomment-161916816>
> .
>



-- 
-------------------------------------------------------------------------------
Carl J. Nobile (Software Engineer)
carl.nobile@gmail.com
-------------------------------------------------------------------------------

**Comment by cnobile2012** [comment]
Found what looks like a serious issue with the resultant error messages when using  @blazdivjak 's code. This did not happen when I was instantiating the model in a validator and calling clean().

I am getting this `['{\'char_definition\': [u"Invalid format, found separator \':\' in \'T:\\\\d\\\\d\'"]}']`. The dict is getting serialized (not JSON compatible) then dropped into a list. This will be pretty useless when a client gets it.

Any ideas?

**Comment by xordoquy** [comment]
Please, let's move usage questions to the discussion group.

**Comment by blazdivjak** [comment]
To trigger validation on your model just add this functions to your model class:

    def clean(self):

        self.function1()
        self.function2()
        self.function3()

    def save(self, *args, **kwargs):

        self.full_clean()
        super(Example, self).save(*args, **kwargs)

And to display errors to your api client your Mixin could look something like:
...
    def perform_update(self, serializer):

        try:
            instance = serializer.save()

        except ValidationError as e:
            non_field_errors = e.message_dict[NON_FIELD_ERRORS]
            msg = {'non_field_errors':  non_field_errors}
            raise ValidationError(msg)

**Comment by coriolinus** [comment]
I've run into a case where it's a bit troublesome to manually coerce Django's `ValidationError`s into DRF's: password validation using the [`validate_password`](https://docs.djangoproject.com/en/1.10/topics/auth/passwords/#django.contrib.auth.password_validation.validate_password) function. @gabn88 's solution handles it, but I wish there were a better way to coerce the one into the other.

**Comment by cnobile2012** [comment]
The way I have solved this issue is actually very straight forward, but has many little pieces.

I try as best as possible to do all validation in the `clean` method in the models, then be sure the `clean` method is called appropriately. The reason for doing validation in the model is so you don't repeat the validation all over the place, in Django forms, DRF serializers, etc. This will keep your code as DRY as possible. For example:

I define a mixin:

    class ValidateOnSaveMixin(models.Model):

        class Meta:
            abstract = True

        def save(self, *args, **kwargs):
            self.full_clean()
            super(ValidateOnSaveMixin, self).save(*args, **kwargs)

Then use it in all models that have a `clean` method. Be sure `ValidateOnSaveMixin` is at the end of the MRO (farthest on the right) or things could get nasty if you use multiple mixins. You would then raise your Django `ValadationError`(s) in the `clean` method below.

    class MyModelClass(ValidateOnSaveMixin):
        ...

        def clean(self):
            ...

Then I create two more mixins for the API views:

    from django.core.exceptions import ValidationError as DjangoValidationError
    from rest_framework.serializers import ValidationError

    class TrapDjangoValidationErrorCreateMixin(object):
        def perform_create(self, serializer):
            try:
                instance = serializer.save()
            except DjangoValidationError as detail:
                raise ValidationError(detail.message_dict)

    class TrapDjangoValidationErrorUpdateMixin(object):
        def perform_update(self, serializer):
            try:
                instance = serializer.save()
            except DjangoValidationError as detail:
                raise ValidationError(detail.message_dict)

There are many different objects to use when you raise the DRF `ValidationError`. They will give you different objects, some usable and some not so much. I used `detail.message_dict`.
```
    detail.error_dict
￼    detail.message
￼    detail.message_dict
￼    detail.messages
```
Lastly use the appropriate view mixin in the appropriate view. For eample:

    class MyListView(TrapDjangoValidationErrorCreateMixin,
                                 ListCreateAPIView):
        ...

    class MyDetailView(TrapDjangoValidationErrorUpdateMixin,
                                    RetrieveUpdateAPIView):
        ...

 That should do the trick.

**Comment by gabn88** [comment]
@cnobile2012  It is good to see another way to handle this :)

For me, personally, it wouldn't work since I have overriden the save method on almost all models. Not sure if that is a good practice though.

**Comment by cnobile2012** [comment]
@gabn88 Overriding the save method with a `fullclean()` call in it is what most people do, however, as I mentioned in my post it has potential problems when there are other model mixins that auto populate other fields in the model. This is why I use the `ValidateOnSaveMixin` mixin at the end of the MRO.

Anyway, if what you are doing seems to work fine then it is a much simpler approach.

**Comment by knaperek** [comment]
I like @cnobile2012 's answer but would suggest a couple of changes for cleaner OOP.

First, the `ValidateOnSaveMixin` should not inherit from Django Model but rather a pure `object`. Why presume anything about the concrete model ancestry that only makes things rigid when we have duck typing? This way you also avoid the mentioned problems with MRO and don't have to put it at the end.

So just define a **pure mixin** first:

```python
class ValidateOnSaveMixin(object):
    def save(self, *args, **kwargs):
        self.full_clean()
        super(ValidateOnSaveMixin, self).save(*args, **kwargs)
```
And then your model:
```python
class MyModelClass(ValidateOnSaveMixin, models.Model):
    ...

    def clean(self):
        ...
```

Similarly, let's not break the OOP inheritance flexibility with the `TrapDjangoValidationErrorCreateMixin` and simply call `super` in `perform_create` **instead of explicitly saving** the serializer.

```python
class TrapDjangoValidationErrorCreateMixin(object):
    def perform_create(self, serializer):
        try:
            super(TrapDjangoValidationErrorCreateMixin, self).perform_create(serializer)
        except DjangoValidationError as detail:
            raise ValidationError(detail.message_dict)
```
This allows for further customization of your `MyListView`, e.g. if you want to set some defaults in an overridden `perform_create` method:
```python
class MyListView(TrapDjangoValidationErrorCreateMixin,
                             ListCreateAPIView):
    def perform_create(self, serializer):
        ...
        return serializer.save(user=self.request.user)  # Just an example, you can obviously do anything
```
Even if you don't override the `perform_create` method on your `MyListView`, you can rest assured that the serializer **will be saved** automatically by parent classes. `ListCreateAPIView` inherits from `CreateModelMixin` which [saves](https://github.com/tomchristie/django-rest-framework/blob/3.5.3/rest_framework/mixins.py#L26) the serializer already. You should always strive to get the full ancestry of overridden methods executed unless you have a very good reason not to. This way your code stays DRY and robust against changes.

The same goes for `TrapDjangoValidationErrorUpdateMixin`.

**Comment by cnobile2012** [comment]
@knaperek, The main issue I have with your comment. Is dealing with the MRO.

The `ValidateOnSaveMixin` mixin would still need to be at the end of the MRO, actually just before `models.Model`. If not put there any DB fields brought in and set to a value from other mixin's that would be after `ValidateOnSaveMixin` would not be run before the `full_clean` causing all saves to blow up. Understanding how the MRO works is essential here.

Of cause, if you never pull in other fields and set them you would never notice the issue.

Fixing the mixins were good catches, thanks.

**Comment by dmugtasimov** [comment]
@tomchristie I do not think that forcing DRF users to put validation into API is a good idea. There cases when you need the same validation work from API, web-forms (from Django Admin for example) and CLI. Developers have to either duplicate the code or produce work-arounds like the one posted in the comments.

P.S. BTW, field level validation defined in models is still used by DRF, so you are not completely consistent about not having validation in Django models.

**Comment by cnobile2012** [comment]
Take this back to the original question where @brianmay asked about catching ValidationError(s) in the serializer create and update methods. Think about this scenario where the serializer has been used to not save to a database, but to third-party APIs. Those APIs may return error condition that the serializer will need to pass on to the end-user. Some of these errors can be encapsulated into another error serializer or may just need to raise a ValidationError. There would be no choice but to raise an exception, in this case, in the create or update methods.

Here at Cisco, we have hundreds of APIs that are always being aggregated into yet another API.

**Comment by gabn88** [comment]
I think I might have a new solution to this problem. Instead of adding a mixin, I now have added a custom_exception_handler, and it seems to work fine for now!

```
def improved_exception_handler(exc, context):
    """
    Based on the default DRF views.exception_handler

    Now also handles validation errors on the save and delete functions.

    """
    if isinstance(exc, Http404):
        exc = exceptions.NotFound()
    elif isinstance(exc, PermissionDenied):
        exc = exceptions.PermissionDenied()
    elif isinstance(exc, ValidationError):
        try:
            exc = exceptions.ValidationError(exc.message, exc.code)
        except AttributeError:
            exc = exceptions.ValidationError(exc.messages)

    if isinstance(exc, exceptions.APIException):
        headers = {}
        if getattr(exc, 'auth_header', None):
            headers['WWW-Authenticate'] = exc.auth_header
        if getattr(exc, 'wait', None):
            headers['Retry-After'] = '%d' % exc.wait

        if isinstance(exc.detail, (list, dict)):
            data = exc.detail
        else:
            data = {'detail': exc.detail}

        set_rollback()
        return Response(data, status=exc.status_code, headers=headers)

    return None
```

**Comment by akshay-testpress** [comment]
Can someone clarify me on this? I using `forms.Form` for the form. I have added a validator for a field, validators=[validate_name]. Just to handle validation globally. I'm getting a 500 server error.

How can I make it work gracefully.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take usage questions. Thanks!

**Comment by HansBambel** [comment]
> I think I might have a new solution to this problem. Instead of adding a mixin, I now have added a custom_exception_handler, and it seems to work fine for now!
> 
> ```
> def improved_exception_handler(exc, context):
>     """
>     Based on the default DRF views.exception_handler
> 
>     Now also handles validation errors on the save and delete functions.
> 
>     """
>     if isinstance(exc, Http404):
>         exc = exceptions.NotFound()
>     elif isinstance(exc, PermissionDenied):
>         exc = exceptions.PermissionDenied()
>     elif isinstance(exc, ValidationError):
>         try:
>             exc = exceptions.ValidationError(exc.message, exc.code)
>         except AttributeError:
>             exc = exceptions.ValidationError(exc.messages)
> 
>     if isinstance(exc, exceptions.APIException):
>         headers = {}
>         if getattr(exc, 'auth_header', None):
>             headers['WWW-Authenticate'] = exc.auth_header
>         if getattr(exc, 'wait', None):
>             headers['Retry-After'] = '%d' % exc.wait
> 
>         if isinstance(exc.detail, (list, dict)):
>             data = exc.detail
>         else:
>             data = {'detail': exc.detail}
> 
>         set_rollback()
>         return Response(data, status=exc.status_code, headers=headers)
> 
>     return None
> ```
> 
> Or, even cleaner: Create your own UserInputValidationError, based of django's ValidationError that you can use in the custom exception handler.

Thanks @gabn88. This helped a lot. I also activated this handler as the default in `settings.py`:
```
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "my_app.exceptions.improved_exception_handler",
}
```
