### ISSUE TITLE
Django REST framework as a Github organization

### ISSUE THREAD

**Issue by maryokhin** [encode/django-rest-framework#2162]
I noticed that recently a lot of packages are moving away from the core to different repositories. While I think that is the right way to go, the packages are kind of drifting away in various directions. Of course, I can read the documentation to find the links, but as a casual user I can't just poke around Github and find them. The framework is getting bigger, has docs, a website and now a growing network of packages. 
For example, this is <a href="https://github.com/django">Django</a>'s organization.

Why I thought it is important now, is because before all the links and package repos have settled down it might be a good idea to think about. You can start throwing shoes at me now :)

**Comment by sheppard** [comment]
FWIW, it looks like GitHub will automatically redirect links to a moved/renamed repository (even after an ownership transfer) - as long as you don't replace it with a new placeholder repository (which would otherwise make sense).  The one really awkward thing though is that @tomchristie wouldn't be able to fork the moved DRF repos without breaking the redirects.  I tried this out on a test repository:

 - Create a repository under my account.
 - Move repo to an org account -> Redirect automatically set up
 - Create placeholder repo in my repository with same name as original -> No redirect (obviously)
 - Delete placeholder repo ->  Redirect works again (!)
 - Fork org repo to my account -> No redirect (since fork has same name as original location)
 - Rename fork so it doesn't match org repo ->  Redirect still goes to fork
 - Delete fork -> Redirect goes back to org repo.

**Comment by xordoquy** [comment]
Bumping the issue. Def makes sense. Sentry has moved to an organization a while ago as well.

**Comment by tomchristie** [comment]
Becoming an org I'm totally happy with. I think we should tie that to a major release. I don't see any particular reason why that couldn't be the next one, or else have it be the one in which the last bits of kickstarter work reach completion, as a milestone marker. "Okay this project belongs to the community now".

I think this issue is distinct from third party packages - I don't really want to see those under the org but we can absolutely do a way better job of surfacing them and keeping it current. A big prominent table in the docs that is automatically populated from django packages would help there.

**Comment by xordoquy** [comment]
I think I need to think a bit more about how we could handle the 3rd party packages and how we could help them for the version upgrades.

**Comment by tomchristie** [comment]
I've milestoned this for 3.2.0 for now, but it may drop to 3.3.0.

**Comment by ar45** [comment]
http://git-scm.com/docs/git-submodule is the way to ho for third party apps

**Comment by xordoquy** [comment]
@ar45 submodules are something different. They are to simulate a single repository when there are several of them.
We don't want to include 3rd parties in the DRF release but make their life easier while DRF evolves.

**Comment by tomchristie** [comment]
Bumping this for consideration.

**Comment by tomchristie** [comment]
Strongly considering moving us over to https://github.com/encode

**Comment by auvipy** [comment]
tom, move forward :+1:

**Comment by tomchristie** [comment]
Done.

**Comment by xordoquy** [comment]
Thank you.

**Comment by auvipy** [comment]
it would be nice to see more drf related projects under encode umbrella :)
