### ISSUE TITLE
Allow non-text `detail` argument for APIException.

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/django-rest-framework#2341]
In 2.x exception strings were not translatable. In 3.0 this was fixed and force_text was included to evaluate the translation strings. As a side effect this broke free-form exception styles that were unintentionally supported in 2.x.

We should decide if we want to support free form exception styles. Generally my preference would be not, but on the other hand it'd be an easier upgrade from 2.x if we do.

See also: https://github.com/tomchristie/django-rest-framework/pull/2055

**Comment by nottrobin** [comment]
The use-case that I have, and the reason why I've decided not to upgrade to version 3 because of this feature, is because I wanted to be able to output nicely formatted ASCII inside my JSON, for nice little easter eggs, e.g. 404 pages:

```
{
    "detail": [
        "  /\_/\     ",
        "=( °w° )=   ",
        "  )   (  // ",
        " (__ __)//  "
    ]
}
```

I was trying to attach these little easter eggs to some special error conditions. I understand that this is not a good *technical* reason why this feature should be included.

**Comment by tomchristie** [comment]
> I understand that this is not a good technical reason why this feature should be included.

Easy to do, but you'll want to subclass APIException, rather than use the default if you want to allow non-string `default` arguments. :)

Note that the other way around to handle this is to write a custom exception handler: http://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling

Eg you could choose to respond to all 404s with your custom content, regardless of the detail string in the exception.

**Comment by nottrobin** [comment]
@tomchristie okay, it sounds like I want to subclass `APIException` as you say. If I do that, is it easy for me to tell all `djangorestframework` exceptions to use my subclass rather than the default for all extended exceptions? (e.g. `AuthenticationFailed`)

**Comment by nottrobin** [comment]
@tomchristie okay [I've extended `AuthenticationFailed`](https://gist.github.com/nottrobin/5b7fc7fd8ae08c2b1ea3) (as it's all I need right now) to not `force_text` for custom descriptions.

Thanks for your help.

**Comment by tomchristie** [comment]
> to tell all djangorestframework exceptions to use my subclass rather than the default for all extended exceptions

That wouldn't really make any sense - you're not going to be able to force the code raising those exceptions to instantiate them with some other arguments for 'detail'.

You can either customize how you handle the existing set of exceptions that are raised, or you can define new ones that you raise in your own codebase.
