### ISSUE TITLE
ModelSerializer caching.

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#2504]
Cache the set of fields generated by a ModelSerializer class so that future instantiations are faster. See #2324. We should evaluate the performance of this, to determine if it makes a noticeable difference.
If so, also consider adding to the release announcement. If not, reconsider if we want this.

**Comment by thedrow** [comment]
I'm working on a benchmark suite for the serializers.
Don't merge this till I finish if you want to measure performance.

**Comment by xordoquy** [comment]
@tomchristie do you want I give the metaclass another try ?
Reminder: the general idea I had with metaclass was to generate a "regular" `Serializer` from a `Model`.

**Comment by tomchristie** [comment]
@xordoquy I'm not sure what you mean - ModelSerializer is just a regular Serializer with a bunch of automatically generated fields.

**Comment by tomchristie** [comment]
Dropping the milestones on this - we can focus on performance improvements for 3.2, as we may have some more comprehensive benchmarking/profiling for that.

**Comment by JockeTF** [comment]
I've been looking into how to speed up our API. So, today I played around a little bit with field caching for serializers using monkey patching and DRF 3.1.1. These are very informal tests, but perhaps they can provide a little bit of insight.

```python
def patch_get_fields(original_method):
    cache = dict()

    def get_fields(self):
        if self.__class__ not in cache:
            cache[self.__class__] = original_method(self)

        if SHALLOW_COPY:
            return {k: copy(v) for k, v in cache[self.__class__].items()}
        else:
            return deepcopy(cache[self.__class__])

    return get_fields

ModelSerializer.get_fields = patch_get_fields(ModelSerializer.get_fields)
```

Note that our system makes *very* heavy use of nested serializers, which is why I tested with both deep and shallow copies of the fields. The results are calculated by taking the average request time (out of 100 requests) for the heaviest request that our clients make.

Fast CPU (Intel Core i5-3320M, uncapped, turbo enabled):
```
      No field caching: 270 ms
   Caching (deep copy): 260 ms,  ~4% speedup
Caching (shallow copy): 235 ms, ~15% speedup
```

Slow CPU (Intel Core i5-3320M, capped at 36%, turbo disabled)
```
      No field caching: 714 ms
   Caching (deep copy): 678 ms,  ~5% speedup
Caching (shallow copy): 628 ms, ~14% speedup
```

**Comment by carltongibson** [comment]
I've opened #5614 to investigate Benchmarking and Performance Improvements. I'm going to close this as blocked pending that. As and when we get a decent benchmarking solution in place we will revisit this and the other related performance issues.
