### ISSUE TITLE
initialize_request in view.py converts the request in Request without checking the incoming request type

### ISSUE THREAD

**Issue by thedarklord1** [encode/django-rest-framework#2771]
I am trying to call a class baed view from another class based view using [This SO](http://stackoverflow.com/questions/14956678/django-call-class-based-view-from-another-class-based-view) post. I called a class baed view by passing in the request like `MyClassBasedView.as_view()(request)`. When I tried to access the HTTPRequest from request, I had to access it like request._request._request, instead of request._request. I checked the code in views.py and it is converting the incoming request to Request without checking the instance of request. I managed it by using `MyClassBasedView.as_view()(request._request)`
This is my first reporting of an issue. Please be gentle if I violated any guideline.

**Comment by tomchristie** [comment]
Calling a view from another view isn't really supported behavior so odd things may happen, but we *could* modify the behavior you saw eg. by modifying https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L138 slightly so that passing a `Request` to `Request` uses the only underlying `HTTPRequest`, rather then ending up with the convoluted `._request._request`.

There might also be some cases where that'd be helpful if folks are manually constructing `Request` instances in test cases and passing them to the view.

I'm slightly unclear *why* you'd need to access the underlying `HTTPRequest` instance tho, as the proxying behavior we provide should generally ensure that it's not needed.

**Comment by olivergeorge** [comment]
I think this is related to a use case I'm trying to solve which is effectively [batching up data from many views](https://groups.google.com/forum/?fromgroups#!topic/django-rest-framework/39aJuJLpVmw).

**Comment by tomchristie** [comment]
If we do nothing else we should at least raise an error in this case.
