### ISSUE TITLE
Checkbox does not work in HTML form

### ISSUE THREAD

**Issue by dvinegla** [encode/django-rest-framework#2851]
When checkbox is checked, field is passed to validated_data, but when checkbox is unchecked, field is omitted.

**Comment by tomchristie** [comment]
This is simply a constraint of HTML form input.
We should document this in `BooleanField`.
See also similar tickets #2829 and #2894.

**Comment by hyliker** [comment]
@dvinegla @tomchristie  I found same issue about checkbox in html form.  When I try to update a object  in the rest default form, it will trigger the PATCH request,  e.g my model has a boolean field named is_enabled, When is_enabled checkbox is unchecked, the PATCH request won't include the is_enabled data, so internal partial update method  won't change the is_enabled field. I mean no way to change the is_enabled to False in current rest form.  This issue is caused by checkbox.html in the  rest templates.  rest_framework/horizontal/checkbox.html.  

and the solution is to add a hidden field with same name before the checkbox. so that when checkbox is unchecked, it will pass the hidden field value (false),  and checkbox is checked, it will override hidden field value.  and it works :)
```
   <input type="hidden" name="{{ field.name }}" value="false" />
   <input type="checkbox" name="{{ field.name }}" value="true" {% if field.value %}checked{% endif %}>
```

**Comment by xordoquy** [comment]
The HTML constraint is stated in the [documentation](http://www.django-rest-framework.org/api-guide/fields/#booleanfield) now:
> This is because HTML checkbox inputs represent the unchecked state by omitting the value

@hyliker you're free to override DRF's templates in your app. However, I'm reluctant to add such workaround since it would alter the standard behavior of a known HTML field and I believe `NullBooleanField` should solve the issue.
