### ISSUE TITLE
Versioned docs

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#3310]
Requires support in MkDocs

**Comment by kevin-brown** [comment]
Support for this appears to be milestoned in MkDocs, here's the related ticket: https://github.com/mkdocs/mkdocs/issues/193

**Comment by d0ugal** [comment]
I made a short experiment some time ago. It might enable you to do this sooner than you think. It isn't finished, but the key missing feature was theme integration.

https://github.com/d0ugal/mkdocs-versioned

**Comment by xordoquy** [comment]
@d0ugal nice job. I'll try to sandbox that next week.

**Comment by d0ugal** [comment]
No problem! At the moment it is very simple, it will go through each of your git tags and build them to a sub directory. For DRF that is probably a [terrible default](https://github.com/tomchristie/django-rest-framework/tags) and it should perhaps default to the most recent major and minor versions only. Anyway, it will then build them so that `3.3.2` would be available at `/v3.3.2/` and so on. It will build `master` to `/` but that can be replaced with a version of your choice.

Something could be done with [extra](http://www.mkdocs.org/user-guide/custom-themes/#extra-context) to pass the built versions to the themes so that they know which are available and mkdocs-versioned would probably need to add the current version to each build.

There are a bunch of unanswered questions still. Landing this in MkDocs would be hard work, but I'd be more than happy to make smaller changes to unblock you if you think this approach might work and I'm very happy to accept changes to mkdocs-versioned also, I am not currently using it, it was just a proof of concept.

**Comment by d0ugal** [comment]
(... and if this turned out to be a good solution, I'd be happy to move it into MkDocs over time and make sure we have an easy migration strategy for DRF.)

**Comment by tomchristie** [comment]
Actually a lot less of a priority given that we're in long slow stable mode now.
