### ISSUE TITLE
CoreAPI integration for ViewSets ignores http_method_names limits.

### ISSUE THREAD

**Issue by puja9** [encode/django-rest-framework#4691]
## Checklist
- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
           Pypi 3.5.3
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
a. Have attached project to highlight issue [Uses Python 3.5]
     /api/SampleRouteLimited/ will show single method available
     /schema/ shows all methods normal for a viewset

b. Alternatively use an existing viewset.
1. Limit viewset to a single method
      i.e., http_method_names = ['get']    
2. generate schema

## Expected behavior
Only show schema information for requested methods.

## Actual behavior
Returns information for all methods, even if not allowed.

[coreapi_test.zip](https://github.com/tomchristie/django-rest-framework/files/602205/coreapi_test.zip)

**Comment by tomchristie** [comment]
`http_method_names` is an internal implementation detail and is not intended a documented way to restrict which methods may be applied. I would suggest either:

* Use `ReadOnlyModelViewSet`.
* Build your viewset explicitly only including the actions you want... http://www.django-rest-framework.org/api-guide/viewsets/#custom-viewset-base-classes
* Use permission classes to restrict access.

Hope that helps move things forward.

The best place to start with questions like this is usually the discussion group rather than the issue tracker.

All the best,

  Tom

**Comment by alejandrodnm** [comment]
I'm having the same problem, the thing is that I'm excluding only patch in the http_method_names. I'm still using the UpdateModelMixin but I only want the **update** not the **partial_update** method in the schema, because it's making swagger add the patch method that it's really not implemented in this view.

**Comment by tomchristie** [comment]
Reopening for further consideration.

**Comment by hurturk** [comment]
I have attempted implementing this by set intersection, example case provided.

**Comment by rpkilby** [comment]
Would this also need to apply to API docs?

**Comment by hurturk** [comment]
API docs use schema generator so it effects it directly.
