### ISSUE TITLE
Authentication Views for DRF ?

### ISSUE THREAD

**Issue by amineparis** [encode/django-rest-framework#5045]
_New feature suggestion for next release_ 

It would be great to have built-in authentication views that respect security best practices to quickly implement REST authentication system. 

Django has this feature for classic web apps and it works greate but is not suited for Rest Architeture.

Many existing third-party libraries have low quality with lack of customization possibilities

**Comment by xordoquy** [comment]
Can you provide some links about it or more informations ? It's a bit vague in its current form.

**Comment by amineparis** [comment]
*   [Django for classic web apps built-in authentication views](https://docs.djangoproject.com/en/1.10/topics/auth/default/#module-django.contrib.auth.views)
*  [DRF third party failed attempt 1](https://github.com/Tivix/django-rest-auth)
*  [DRF third party failed attempt 2](https://github.com/sunscrapers/djoser)
*  [DRF third party failed attempt 3](https://github.com/James1345/django-rest-knox)

My suggestion is to have a built-in one for DRF

**Comment by amineparis** [comment]
I need serious feedback from repo admins, This would be a huge addition to this amazing framework, it helps thousands of users to gain weeks of work on defining, securing and testing an authentication system.     I am ready to stop work for a months to help make this feature happen

**Comment by xordoquy** [comment]
I'm going to close this due to the lack of actionable content.

A few thoughts:
I don't see how having it within DRF will make it more successful than as a 3rd party.

> Django has this feature for classic web apps

I would argue, so does DRF:

- DRF already provides an [authentication view](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authtoken/views.py#L8) for the Token
- Django already provides views for the `SessionAuthentication`
- `BasicAuthentication` doesn't require a login view.

Any other authentication view is specific to the associated protocol and I don't see how that can be abstracted.

**Comment by tomchristie** [comment]
@amineparis Rather than think of this as "it's not going to happen" consider it as, who's going to undertake this work. If you're keen then go for it - you've obviously got a clear view about what requirements you think it'd need to fulfill.

Personally I think `djoser` and `django-rest-auth` already fill *exactly* the gap you're talking about (with `knox` being a little different) so it's not clear to either me or @xordoquy exactly what concrete changes you'd be suggesting to what either of those two packages currently provide.

**Comment by amineparis** [comment]
@tomchristie a built-in solution would be better integrated with the main framework architecture + it would motivate more contributors to make it great (better customisation possibilities ...)

**Comment by tomchristie** [comment]
Built-in or third party would make no difference to "integration" - it'd purely be about branding at this point. Would totally agree that pulling something under our banner would give it more contributors, but there's no reason for any work here to not start as a third party package, and then have us consider pulling it into core if and when it's clear that it adds sufficient value.

**Comment by xordoquy** [comment]
I don't think anyone of us would object giving its opinion and performing reviews for any 3rd party that would request.
As I said, I don't see how moving something into core would make it more successful / integrated.
Django-filters isn't part of DRF and yet is very well integrated.
