### ISSUE TITLE
`_get_object_or_404` can mask errors, and return 404 instead.

### ISSUE THREAD

**Issue by sonus21** [encode/django-rest-framework#5110]
IMHO, error handling for 404 should be changed.
When get_queryset returns object instead of queryset then it raises 404 with message {"detail":"Not found."} even though debug is enabled(DEBUG=True) but nothing happens, it was still raising 404 error with the same response.

Resolving such problem is tedious since you have no clue what's wrong unless you sit back and scan again. 

It would be better if we could have raised other errors instead of this, semantically this's wrong since get_queryset is returning object/None instead of queryset.

**Comment by tomchristie** [comment]
We could assert that the correct type is passed here... https://github.com/encode/django-rest-framework/blob/master/rest_framework/generics.py#L19

I assume that Django's `get_object_or_404` correctly raises a type error when passed a model instance, but that we catch it because we need to catch the case where URL kwargs are used that cannot be coerced to the correct type (eg. a numeric field that's looked up using "abc")

**Comment by sonus21** [comment]
Yes, we should either assert it or handle it appropriately.

I don't think Django is catching 404 exception and sending a response since the response returns by Django for 404 is different than this https://github.com/django/django/blob/301de774c21d055e9e5a7073e5bffdb52bc71079/django/views/defaults.py#L18 .

**Comment by auvipy** [comment]
May I know the current update of the issue? what is the current recommendation for this?

**Comment by shywn-mrk** [comment]
Is this still relevant? I'm thrilled to contribute.
If so, can you please give me some updates about the current situation?
