### ISSUE TITLE
test dependencies broken on python 3.6?

### ISSUE THREAD

**Issue by rpkilby** [encode/django-rest-framework#5116]
~~Apparently skipping in python 3.6 is broken with pytest~~. See: 
https://travis-ci.org/encode/django-rest-framework/jobs/228249355
vs
https://travis-ci.org/encode/django-rest-framework/jobs/228249343

**Comment by tomchristie** [comment]
Sorry, walk me through what I'm missing there? I can see a different number of skipped cases in each, is that what you're referring too? (But *some* skipped in each case)

That could be due to eg. different available dependencies in diff environments right? (haven't looked into what skips we currently have in place)

**Comment by rpkilby** [comment]
Actually, it looks like `django_filters` isn't being imported for whatever reason. eg, in `test_filters.py`
```python
raise Exception('!!!!', django_filters)
```
raises None

**Comment by rpkilby** [comment]
And tox *is* installing django-filter 1.0.0 - see line [154](https://travis-ci.org/encode/django-rest-framework/jobs/228249355#L154). Checking the env locally, `ls .tox/py36-django111/lib/python3.6/site-packages/` `django_filters` is also present...

**Comment by rpkilby** [comment]
nvm - it seems to be an interaction with django-filter 1.0.0 and django 1.11
Updating the optional requirements fixes this.
