### ISSUE TITLE
Django rest framework docs does not support links of the third and above level of nesting, like company/id/positions/ 

### ISSUE THREAD

**Issue by alex1vanchik** [encode/django-rest-framework#5123]
Django rest framework docs does not support links of the third and above level of nesting, like company/id/positions/ . I think that is a very important for this dock functionality. I'm not sure that is a mistake, maybe that just don't developed yet. My question is - do you plan to develop this? And if yes, in which version?

**Comment by xordoquy** [comment]
We do not plan to implement such feature. We believe that nested urls are not a good practice when designing APIs because it duplicates entry points.
We usually advice to take full use of filtering features to keep API DRY and gain more flexibility.

In short:

    /api/project/{project_id}/milestone/{milestone_id}/tasks

could be rewritten as:

    /api/tasks?project={project_id}&milestone={milestone_id}

If you still do want to use nested urls, there is at least one 3rd party that implements this feature.
