### ISSUE TITLE
Ability to specify renderer for the "Interact" form response

### ISSUE THREAD

**Issue by tdruez** [encode/django-rest-framework#5145]
In the new "Built-in interactive API documentation", using the "Interact" forms, how can I force the response to be rendered as JSON instead of rendered as Django page, since my default renderer_class is BrowsableAPIRenderer (comes in first in the DEFAULT_RENDERER_CLASSES list, and the JSONRenderer is second). In other words, how can I make the Interact form to include `format=json` in the request.

## Steps to reproduce
```
# settings.py
'DEFAULT_RENDERER_CLASSES': (
    'rest_framework.renderers.BrowsableAPIRenderer',
    'rest_framework.renderers.JSONRenderer',
),
```

In the new interactive API documentation:
- click on "Interact"
- fill the form
- the reponse is a Django renderer HTML

## Expected behavior
I should be able to force a JSON response, through a renderer setting or by passing `format=json` to the Interact request.

**Comment by matteius** [comment]
@tdruez I have searched Google for `DJEBrowsableAPIRenderer` and found only this bug report.  I will assume that is your own custom sub-class of `BrowsableAPIRenderer` to try and force the UI to render a ?format=json response.   On the one hand this kind of feels like a feature request, or maybe a stack overflow question on how to accomplish this with your own sub-class of `BrowsableAPIRenderer` though I am not sure that would even be necessary.   

 I am running a test project locally at PyCon which is currently v3.6.3 and I see that in the Browseable UI API there is an option to specify the return type.  I will attempt to include a screen shot of this feature:
![image](https://cloud.githubusercontent.com/assets/479892/26328054/8dfa1968-3f0f-11e7-8e96-83bfe4fe2783.png)
 
When I select the json response I am returned to the json rendering of the page which bypasses the `BrowsableAPIRenderer` to use `JSONRenderer`.  Both classes need to be defined in your `DEFAULT_RENDERER_CLASSES` setting in order to be available for use.

**Comment by xordoquy** [comment]
@matteius we're not speaking about the browsable API here, it's about http://www.django-rest-framework.org/topics/3.6-announcement/#interactive-api-documentation.
As far as I can tell, it seems to take the first renderer. I'm pretty confident that settings the BrowsableAPI as first renderer would break it as it doesn't seem to enforce a content type - accept header is set to */*.

**Comment by brjadams** [comment]
@xordoquy you suspect correct regarding the BrowsableAPIRenderer.

There are two suggested routes to workaround this problem.
1.) Put the JSONRenderer first, essentially making it the default renderer. Perhaps you don't want the BrowsableAPIRenderer anymore since you are using the interactive views.
For Example:
```
'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
```

2.) The sure-fire path is to explicitly set the renderer class directly on the view via `renderer_classes = [JSONRenderer]` or via a mixin that sets the renderer.

**Comment by xordoquy** [comment]
@brjadams those are two short term fixes but the overall system should not rely on this as we can set the content type to do better than that.

**Comment by tdruez** [comment]
@brjadams I want to keep use the BrowsableAPIRenderer as my first rendered, it's still very valuable and does not serve the same purpose as the new API documentation.

@xordoquy I'm with you on the solution, I think we should be able somehow to set the proper content type header for that interactive request.

**Comment by tomchristie** [comment]
We're going to continue to use whichever the default renderer is. There no good reason to prioritise the browsable API over JSON, as the browser will send the correct Accept header to choose an HTML rendering if it exists.
