### ISSUE TITLE
DRF: serializers.DictField Error(AttributeError: 'str' object has no attribute 'items')

### ISSUE THREAD

**Issue by ranvijay-sachan** [encode/django-rest-framework#5151]
http://stackoverflow.com/questions/44038126/drf-serializer-fields-dictfield-attributeerror-str-object-has-no-attribute/44038373?noredirect=1#comment75104297_44038373

**Comment by xordoquy** [comment]
Hi, you may have stored a string instead of a dictionary in the JSONField. Using a [JSONField](http://www.django-rest-framework.org/api-guide/fields/#jsonfield) may help.
I'm closing this because we're lacking actionnable content.
If you think it's a bug in DRF, the next step would be to reduce the use case to the simplest test case we could check and we'll reconsider by then.

**Comment by ranvijay-sachan** [comment]
if we add jsonfield(binary=true)
its work.

But if I send actual JSON in payload then it shows it's not a valid JSON.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by Old-fashionedmatthew7** [comment]
i stumbled upon the answer



https://stackdev.space/questions/drf-attributeerror-unable-to-access-pk-attribute-as-it-does-not-exist-in-the-str-object
