### ISSUE TITLE
Random ModelSerializer behaviour

### ISSUE THREAD

**Issue by SudhagarS** [encode/django-rest-framework#5269]
## Steps to reproduce
I have a model with four fields. One is boolean where blank is allowed and three others are required char fields. I have a model serializer that uses this model. In serializer meta, I have `fields='__all__'`

1. I instantiate the serializer with `instance=None`, `partial=True` and `data={}`. Now I do `serializer.is_valid()`
2. I change meta field `fields` to (`char_field2`, `char_field3`, `boolean_field`)

## Expected behavior
1. `serializer.errors` should have a dict with three keys in it. 
2. `serializer.errors` should have a dict with two keys(`char_field2`, `char_field3`) in it. 

## Actual behavior
1. `serializer.errors` is this  {'char_field1': [u'This field is required.'], 'char_field2': [u'This field is required.']}
2. `serializer.errors` now contains  {'char_field1': [u'This field is required.'], 'char_field2': [u'This field is required.'], 'char_field3': [u'This field is required.']}

**Comment by tomchristie** [comment]
There's not really enough information in the ticket for us to be able to help, but it certainly looks like a usage issue rather than a bug. I'd suggest asking the question on https://groups.google.com/forum/#!forum/django-rest-framework and either:

* Include an example the serializer class you're using.
* Try to reduce your question to the simplest possible case.

(2) clearly looks like a misconfiguration - there's no way `char_field1` would be referenced otherwise, so it may just need a second set of eyes on your code to help figure out what's not quite right.

**Comment by xordoquy** [comment]
Let's do some guesswork here. Your model has a `unique_together` constraint, possibly on (char_field1, char_field2).

**Comment by SudhagarS** [comment]
@xordoquy Yup, that's exactly the case.

My requirement is, I want the response to contain errors that all three fields are missing.

**Comment by xordoquy** [comment]
@SudhagarS I'd suggest you move the thread to the mailing list as it is a usage question.
Would also be good to provide more informations about your goal.

**Comment by SudhagarS** [comment]
@xordoquy I am not sure. 

See, the default behavior in rest framework is sending error related to all the fields in response. Like in my case, I expect the response to say `char_field1`, `char_field2` and `char_field3` are required and but they are missing.

Now that there is a `unique_together` constraint, it breaks the default behavior.

**Comment by xordoquy** [comment]
You misunderstood what `partial` is for.

**Comment by SudhagarS** [comment]
@xordoquy ah, got it. 👍
