### ISSUE TITLE
returning QueryDict with content-type application/json and empty body

### ISSUE THREAD

**Issue by Reskov** [encode/django-rest-framework#5349]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Hi, is this line correct? 5677d06#diff-6dc9b019ec1d96c56e0e31dac3bba51cR302

This line of code was added at this pull request.

if media_type and not is_form_media_type(media_type):
      empty_data = QueryDict('', encoding=self._request._encoding)
else:
      empty_data = {}

## Expected behavior
I suppose returning QueryDict should be only for form data type, not for application/json. 
## Actual behavior
In my case I was sending empty request with content-type application/json and received immutable QueryDict(). Is this correct behaviour?

**Comment by rpkilby** [comment]
Hi @Reskov. Yep - I think you're correct here. The condition should be
```python
# this
if media_type and is_form_media_type(media_type):
    ...

# not this
if media_type and not is_form_media_type(media_type):
    ...

```

I did a little debugging, and it looks like the test client isn't setting the request's `content_type`. Because of this, the condition fails on the first part of the expression, and not on the `is_form_media_type` check.

Digging further, this is a behavior of the Django's builtin `RequestFactory`. The `CONTENT_TYPE` header is only set if data is [provided](https://github.com/django/django/blob/1.11/django/test/client.py#L402-L407).

**Comment by rpkilby** [comment]
Hi @Reskov - PR 5351 should fix the issue. If you have the time, could you install the corresponding branch and verify the expected behavior?

**Comment by Reskov** [comment]
Hi @rpkilby, I already verified your branch localy, seems problem is gone, thank you
