### ISSUE TITLE
invalid template

### ISSUE THREAD

**Issue by kakulukia** [encode/django-rest-framework#5463]
im getting this error compressing my files:

    Invalid template ..../site-packages/rest_framework/templates/rest_framework/filters/django_filter_crispyforms.html: 'crispy_forms_tags' is not a registered tag library. Must be one of:

Is django-crispy-forms a required lib? Why ist it not installed as dependency?
Python3.6 / DRF 3.6.4

**Comment by tomchristie** [comment]
It's optional. Install it if you want to use the crispy forms filter.

**Comment by kakulukia** [comment]
@tomchristie  in not using crispy forms but still get the error :(
Its visible when i compress my source files with the following command:

    manage.py compress -e pug,html --force

Its somehow picking up this template tho im not using it.

**Comment by tomchristie** [comment]
Reopening for further consideration.
Anyone able to confirm that they can replicate this issue?

**Comment by carltongibson** [comment]
@kakulukia `compress` that's django-compressor right? 

Compressor searches all templates looking for `{% compress %}` blocks. So even though you're not using crispy forms, it's still going to look at those templates. 

Short of putting together a template finder that skips these files I don't see a way round this... — it's just a coming together of a group of third-party libraries. 

**Maybe** it's worth opening an ticket on Django Compressor, saying "skip this kind of error during compress". 

I'm not sure that's worth the extra complexity there because...

Your simplest solution is to install crispy forms (and add it to INSTALLED_APPS) so that the `compress` command can find the tag library, and then move on. 

This isn't a DRF issue. (As per above, at best, it's a compressor issue.) 



I feel strangely at home on this ticket...

**Comment by kakulukia** [comment]
i filed an issue at django-compressor, they really might be able to search differently for their compress tags

thx

**Comment by rpkilby** [comment]
As a side note, the django-filter templates should have been removed back in v3.5 but were accidentally left in. #5465 should fix this for the upcoming v3.7 release.
