### ISSUE TITLE
Throttle does not work correctly under load

### ISSUE THREAD

**Issue by haos616** [encode/django-rest-framework#5494]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Send at the same time many requests for a point with throttle

## Expected behavior
Throttle will not miss more requests than set

## Actual behavior
Throttle can skip a large number of requests

## More
Throttle logic save history request in the django cache.
https://github.com/encode/django-rest-framework/blob/c674687782ef96a3bb8466b412e99debd3d04f00/rest_framework/throttling.py#L125-L143
Because of this, it is possible to lose some requests. Example:
```
mport threading
import logging

from django.core.management.base import BaseCommand
from django.core.cache import cache as default_cache

logger = logging.getLogger('app')


class Command(BaseCommand):
    def handle(self, *args, **options):
        cache_key = 'test'

        def test_cache(i):
            history = default_cache.get(cache_key, [])
            logger.debug('Old: %s', history)
            history.insert(0, i)
            logger.debug('New: %s', history)
            default_cache.set(cache_key, history)

        default_cache.set(cache_key, [])
        logger.debug('Start: %s', default_cache.get(cache_key, []))

        for _ in xrange(5):
            thread_ = threading.Thread(target=test_cache, args=(_,))
            thread_.start()

        while threading.active_count() > 1:
            pass


        logger.debug('End: %s', default_cache.get(cache_key, []))
```

```
DEBUG app Start: []
DEBUG app Old: []
DEBUG app New: [0]
DEBUG app Old: []
DEBUG app New: [1]
DEBUG app Old: [1]
DEBUG app New: [2, 1]
DEBUG app Old: [2, 1]
DEBUG app Old: [2, 1]
DEBUG app New: [3, 2, 1]
DEBUG app New: [4, 2, 1]
DEBUG app End: [4, 2, 1]
```
Lost requests 0 and 3

I recommend using lists at storage level. For example, we can use rpush in redis (https://redis.io/commands/rpush).
But for this, we need to add support for lists in the django cache or make your own.

**Comment by tomchristie** [comment]
Yes fair, point, but problematic in that we can't do anything about that without stepping outside of the existing cache framework. I *would* like to see a throttling backend that addresses this, but *because* of the "We can't do that with Django's cache API" constraint, I'd also like to see it start off as a third party package. (We'd include links to it from the main throttling documentation page)

An alternative that *could* use the cache framework would be to use `incr` and `decr`. Eg have per-hour-granularity timestamped buckets, and use the atomic `incr` method to bump up the number of requests in each bucket. This would be a significant change from the existing behavior, and again there's no particular reason why it couldn't start out as a third party package.

Would be very happy to see someone work on a package that implements either of those two ideas (or both!) and would include the package prominently in the docs if that happens.

**Comment by mik3y** [comment]
Hi there! Turns out I implemented something very much like @tomchristie 's idea from the discussion above. Stumbled across this old thread and thought I'd share. Here's the gist:

https://gist.github.com/mik3y/68cc153014333b03c9f21874300a9624

I wrote this because I noticed the stock `SimpleRateThrottle` keeps an ever-growing list of timestamps in each cache entry, which can be space inefficient (especially on a high-load api). The implementation above leverages cache timeouts and `.decr()`, so ends up being quite simple to reason about.

(@xordoquy if this seems interesting to you in core, I could try to find some time to PR. cheers!)
