### ISSUE TITLE
[ IDEA ] Add customizable html parser for list values when submiting Html form data

### ISSUE THREAD

**Issue by shaklev** [encode/django-rest-framework#5515]
I've digged a little bit & seen that in `rest-framework/utils/html.py`, list values from form data are handled inside `parse_html_list` function.  In my case i wanted to use a different notation:

Instead : `[0]foo : 'test'`
I wanted to use `.0.foo : 'test'`

I'n the `parse_html_list` i've replaced `re.compile(r'^%s\[([0-9]+)\](.*)$' % re.escape(prefix))` with `re.compile(r'^%s\.([0-9]+)\.(.*)$' % re.escape(prefix))`  ( changed `[` and `]` with dot ( `.` )) and data is parsed perfectly when using the dotted notation ( `.0.foo : 'test'` ).

I think it would be good to have a configurable option ( preferably in django projects `settings.py` file to choose of different type of html parsers )

P.S. If this somehow will effect the rest of the code i'll be glad if the community shares their opinion on this

**Comment by carltongibson** [comment]
Hi @shaklev 

My initial thought here is that the flexibility isn't worth the added complication, i.e. _"Just use the provided notation"_ — but maybe you want this, so that's not 100%.

I wouldn't be inclined towards a setting here. 

We could **consider** a (documented, tested) PR making `parse_html_list` a class attribute on `ListSerializer` and `ListField`. You could then use subclasses and provide your own function, setting [`list_serializer_class`](http://www.django-rest-framework.org/api-guide/serializers/#customizing-listserializer-behavior) appropriately.
