### ISSUE TITLE
No good way to access nested serializers

### ISSUE THREAD

**Issue by jonathan-golorry** [encode/django-rest-framework#5520]
It would be nice to be able to access child serializers from their parent and have them work as fully functional serializer instances. Using `serializer_instance.fields['<child_name>']` gets the right serializer, but it doesn't have data or a model instance associated with it. From the child serializer, you have to  do something like `self.parent.instance.<child_relation>` to access the model instance.

I understand that there is no intention to support nested writes/updates, but is changing the nesting structure of serializers something that might be done? I think a dynamic-programming-inspired approach would be more intuitive.

BaseSerializer is already a subclass of Field, so it should be possible. I haven't looked into how much of a rewrite it would require, as I wanted to get people's reactions first. Is there a solid reason things aren't done this way?

**Comment by carltongibson** [comment]
(Argh, I seem to be having button trouble this morning.)

Hi @jonathan-golorry. Thanks for the input. 

My first thought is that I'm sceptical about a re-write here. Serializer instances don't pass on their data to their fields such that getting back the field+data complex in a single step. Look at the `is_valid()` call and see how it drives the validation sequence and calls to `to_internal_value()`. It's only here that fields (and so nested serialisers) get passed any data, but they don't hold on to their own copy of it, so even then you can't currently pull out the fully instantiated serialiser that you're looking for. 

Yes, no doubt, a rewrite would be possible, but (for me) helper functions that wrap up the two-step you're looking at would be time more appropriate. (Get data item, get nested serialiser class, create instance, return it.) 

> Is there a solid reason things aren't done this way?

At this point I have to say, _What Way?_ Here it's necessary to see an example of the actual code you might be suggesting. Otherwise I can't say anything. 

I'm going to close this as an issue here. (It's not something we are going to allocate time to ourselves.) 

If you wish to develop this then I suggest you create a base serialiser class that behaves the way you want. If you put that up, either in a PR or (probably better) looking at a third-party package to begin we can review. With code in hand we can see if the benefits are worth the changes. 

Sorry I can't say more without seeing something more concrete.

**Comment by jonathan-golorry** [comment]
>Get data item, get nested serialiser class, create instance, return it.

This is actually what got me thinking about accessing nested serializers. If you start using `source=...` in the fields of nested serializers, that method gets incredibly annoying because your validated data is keyed by the source, not by the field name. You have to re-key it by the field name, re-validate it, etc. This made me run into an issue trying to re-validate a nested serializer in the parent's `update` method, where raising a validation exception caused the parent's validation-catching to kick in, resulting in (if I remember correctly) an error where the parent serializer didn't a field that was declared on the nested serializer.

>What Way? 

I was thinking about going full dynamic programming, so nested serializers would be fully functional on their own and operations on the parent serializer would call the exact same operations on its children, which would then pass the result back up to the parent. It could get confusing in situations where you were changing validated data and things like that, as there's a question of whether each child should get a deep copy of its validated data, etc. I'll see about making a PR or third-party package, but it's a lot of work without having some input from the community.

**Comment by Moulde** [comment]
I am dealing with this issue as well.

In my case, the nested serializer is operating on a list of children and I don't see how the above solution by going through the parent and then accessing the items can work for me, since I have no idea which item I'm currently working on.

I'm trying to access the instance from a validate_field method in the nested serializer.
And my child model is not exposing the primary key of the model, can I somehow make the id of the current model accessible in my validation method, and then look it up via the self.parent?

**Comment by jonathan-golorry** [comment]
@Moulde Can you show the structure of what you're trying to do? I have a lot of workarounds now, but I'm not sure what you're trying to do.
