### ISSUE TITLE
Ability to set default language for interactive docs

### ISSUE THREAD

**Issue by flxfxp** [encode/django-rest-framework#5627]
It would be nice to be able to easily set the default language for the interactive docs to something other than shell. Seems this can't be changed purely on the frontend without some serious javascript hackery.

**Comment by carltongibson** [comment]
Hi @flxfxp. 

It may be that we could take a PR to add some configurability here. But I'm not sure you need serious Javascript hackery... 

This is enough to switch the language: 

     $('#language-control li a[data-language="javascript"]').click()

So you just need to add a ready handler to run that, and you're done. 

I'll add a _help wanted_ label, since there's no harm in a PR, but I'm going to close this as an issue, since it's not something I'd want to allocate time to as active.
