### ISSUE TITLE
Confusing documentation and no code examples for using generic view mixins.

### ISSUE THREAD

**Issue by iMerica** [encode/django-rest-framework#5640]
Hi, this is probably the top DRF question I used to see in my former Python Slack group and I finally  encountered it today. Basically the docs for stuff like [ListModelMixin](http://www.django-rest-framework.org/api-guide/generic-views/#listmodelmixin) are really lacking. There are 15 Generic view classes and only two code examples.

Lets look at api docs for `ListModelMixin` one sentence at a time.

> Provides a .list(request, *args, **kwargs) method, that implements listing a queryset.

This sentence is very confusing. Am I supposed to override this method or just use `get(..)`, then call this method? If I need to override this method, what am I supposed to return?

>If the queryset is populated, this returns a 200 OK response, with a serialized representation of the queryset as the body of the response. The response data may optionally be paginated

How do I populate the queryset? How do I tell this list method which serializer to use?

## Steps to reproduce
- Visit documentation site
- Click API Guide ~> Generic Views.
- Observe that there is full example for using `ListCreateAPIView `
- Click Mixins 
- Observe that examples are missing.
- Observe that theres no link to prerequisite docs that I'm supposed to know about before using mixins.

## Expected behavior
If I had to pick between a description of the mixin or an actual code example using the mixin, I would pick the code example every day of the week, but ideally the API docs would include both.

## Actual behavior
Confusing user experience.

**Comment by xordoquy** [comment]
> Observe that examples are missing.

I think the documentation already covers that with http://www.django-rest-framework.org/api-guide/generic-views/#examples

> Observe that theres no link to prerequisite docs that I'm supposed to know about before using mixins.

Same about http://www.django-rest-framework.org/api-guide/generic-views/#attributes

> If I had to pick between a description of the mixin or an actual code example using the mixin, I would pick the code example every day of the week, but ideally the API docs would include both.

Unfortunately we have code examples - nested serializers for example - and yet the feedback is that it's not enough.
My feeling is what people (including myself) really want is "I want my use case copy-pasted from the documentation" which we can't offer.
Also I'm two folded about it since most will copy / paste, won't bother understanding the why's and come back complaining it doesn't work.

I'm closing this issue as it's not actionable in its current form.
However I'd be happy to discuss documentation improvement in a pull request to see what can be done here.

**Comment by carltongibson** [comment]
I've had success with the simple maxim: 

> "Open [`generics.py`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/generics.py) and have a look." 

I find it opens up a lot for people at that point. 

I don't know exactly where we might put such advice; this issue should be helped by #5636.

**Comment by iMerica** [comment]
Thanks. Lots of helpful information in `generics.py`. 

However, if reading the source is the best way to learn the API, then its good indicator that theres a problem with the content of the docs or the information architecture of the docs.

**Comment by xordoquy** [comment]
I'm looking forward a specific proposal about that topic.

**Comment by carltongibson** [comment]
@iMerica I don't agree at all. The code is clean, and an excellent example to copy when implementing your own views. Coping it into the docs would add nothing. Reluctance to open the source is not a fault of the documentation.
