### ISSUE TITLE
HStore: This field may not be null.

### ISSUE THREAD

**Issue by dungdm93** [encode/django-rest-framework#5644]
## Steps to reproduce
```python
class Product(models.Model):
    title = CharField(max_length=512)
    attributes = HStoreField(null=True, blank=True)

class ProductSerializer(serializers.ModelSerializer):
    class Meta:
        model = Product
        fields = ('title', 'attributes')
```

Some try:
```python
p = Product(title="foobar", attributes={'first': 'value', 'second': None})
p.save()     # Save success. No error here!


# Now, Let's try with Serializer
data = {"title": "foobar", "attributes": {"first": "value", "second": None}}
q = ProductSerializer(data=data)
q.is_valid()
#> False
q.errors
#> {'attributes': ['This field may not be null.']}
```

## Expected behavior
`q` is valid

## Actual behavior
As you can see, `q` is invalid with an error `{'attributes': ['This field may not be null.']}`.  
When I remove `"second": None` from `attributes`. `q` is valid

**Comment by rpkilby** [comment]
This looks to be valid. Django 1.11 added the ability to store nulls as values in addition to strings.

https://docs.djangoproject.com/en/2.0/ref/contrib/postgres/fields/#hstorefield

**Comment by carltongibson** [comment]
Ideally the error message would be more specific too. (It would be nice if `second` were mentioned, so I knew where the problem lay, assuming the `null=False` case.)

**Comment by dungdm93** [comment]
@rpkilby I see. But It would be nice if Rest framework also support this too.

**Comment by rpkilby** [comment]
> Ideally the error message would be more specific too. (It would be nice if `second` were mentioned, so I knew where the problem lay, assuming the `null=False` case.)

I see two possible solutions:
- Prefix all child errors with some common message. 
  `{"attributes": ['Error validating value for key "second": This field may not be null.']}`
- Collect the errors in a dictionary and re-raising those errors on the field. 
  `{"attributes": {"second": ["This field may not be null."]}}`

I'm not a fan of the former, as it seems error-prone to try and modify `ValidationError`s. eg, the `detail` could be a string, dict, or list of messages.

The latter approach is simple, since we just need to store the existing error detail without altering it. 
- probably friendlier for APIs, since you have errors stored by key/index
- probably less friendly to HTML forms, but composite fields already have issues with forms anyway.

**Comment by carltongibson** [comment]
OK, second option looks prettier. 

> probably less friendly to HTML forms, but composite fields already have issues with forms anyway.

Exactly. We have to live with that. HTML forms are what they are. (Not a reason not to do it.)
