### ISSUE TITLE
Support for serializer_class with @api_view

### ISSUE THREAD

**Issue by blueyed** [encode/django-rest-framework#5759]
The WrappedAPIView returned/created by the `@api_view` decorator handles decorators like `@renderer_classes`, but not `@serializer_class`.

Having information about the (input) serializer appears to be important for generating schemas however.

I think this would have helped with the underlying issue that https://github.com/encode/django-rest-framework/pull/4285 fixed, and is maybe also what https://github.com/encode/django-rest-framework/issues/5630#issuecomment-352831405 refers to?!

**Comment by carltongibson** [comment]
Hey @blueyed. This is just the division between `APIView` and `GenericAPIView`. The `api_view` decorator handles the former, but not the latter. (And `serializer_class` is defined on `GenericAPIView`...) 

The comment you link (I was wondering where that was...) is looking for more API (on APIView) to add an extension point for dynamic view inspector class selection, rather than `@ api_view`'s support (or not) of the `GenericAPIView` API.
