### ISSUE TITLE
TypeError: Object of type 'Decimal' is not JSON serializable

### ISSUE THREAD

**Issue by alexanderoskin** [encode/django-rest-framework#5778]
We have a field with JSON (PostgeSQL JSONB) where product prices are specified:
{"total": 2400000, "currency": "USD", "per_meter": 3404}

When we try to filter this field we've got an error:
TypeError: Object of type 'Decimal' is not JSON serializable

https://sentry.io/share/issue/43b4eb682bf64562961f12f60b05f9f6/

django 2.0.1
rest_framework 3.7.7

**Comment by xordoquy** [comment]
Hi, this is an issue tracker.
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take to get help to debug this.
On a side note, we have no idea where / how you built the payload before it goes to the renderer.
I'm closing this issue because it's not actionable in its current form.
