### ISSUE TITLE
djangoobjectpermissionsfilter  Full-text search问题

### ISSUE THREAD

**Issue by xhochipe** [encode/django-rest-framework#5795]
class BlogIndexListViewSet(viewsets.GenericViewSet, mixins.ListModelMixin):

    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    pagination_class = StandardResultsSetPagination
    filter_backends = (DjangoFilterBackend, SearchFilter)
    filter_class = BlogFilter
    search_fields = ('@title', '@content', 'tags__name','category__name')

django.core.exceptions.FieldError: Unsupported lookup 'search' for CharField or join on the field not permitted.

官方doc中提到
    The search behavior may be restricted by prepending various characters to the search_fields.

           '^' Starts-with search.
           '=' Exact matches.
          '@' Full-text search. (Currently only supported Django's MySQL backend.)
         '$' Regex search.
          For example:

          search_fields = ('=username', '=email')

我把字段改成TextField也不行,数据库用的mysql,全文搜索是不是不支持?

**Comment by carltongibson** [comment]
Hi @xhochipe. 

I'm sorry but this issue is not actionable for us as is. Can you try to create a test case which shows your issue? Is so we can look at it. 

Otherwise it looks like a usage question and your best option is to try StackOverflow or the mailing list. 

(Whatever you do you'll need to include the full traceback of your error so people can see where it is coming from.)
