### ISSUE TITLE
Docs: Full Text Search is No Longer MySQL-Only

### ISSUE THREAD

**Issue by Miserlou** [encode/django-rest-framework#5903]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

On this page of the documentation, it says:

> '@' Full-text search. (Currently only supported Django's MySQL backend.)

I think Django has moved on since this was written and that this is now supported in Postgres.

**Comment by tomchristie** [comment]
Thanks for this!

It's still listed as that in the Django docs. https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields

I don't know if:

* That's wrong in the Django docs and needs changing.
* That's correct, and the *particular mechanism* that gets used by the ORM for that type of full-text search is different to the mechanism you'd use for full text search on other DBs.

I'll assume that it's correct in the Django docs and leave our docs as they are, but happy to reopen this if either:

1) Someone can verify/demonstrate otherwise.
2) A ticket against Django gets confirmed as that being a valid docs bug.
