### ISSUE TITLE
CurrentUserDefault NOT NULL database constraint

### ISSUE THREAD

**Issue by alek5k** [encode/django-rest-framework#5943]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
See code in stackoverflow question:
https://stackoverflow.com/questions/49913996/django-not-recognizing-field-override-for-current-user-in-serializer

The usage for this serializer field is outlined on the website:
http://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields

I am only able to get it to work by not making it readonly:
`creator = serializers.PrimaryKeyRelatedField(queryset=User.objects.all(), default=serializers.CreateOnlyDefault(serializers.CurrentUserDefault()))`

## Expected behavior
I expect with that code that the current user should be retrieved and I should not get a NOT NULL constraint error.

## Actual behavior
I get a NOT NULL constraint error.

**Comment by alek5k** [comment]
Can't reproduce fix

**Comment by carltongibson** [comment]
Answered on SO. Since this was a breaking change I'll post the answer here too. 

This is covered in [the release notes for v3.8](http://www.django-rest-framework.org/topics/release-notes/#380).

For read-only fields you need to pass the value when calling save:

```python
def perform_create(self, serializer):
    serializer.save(creator=self.request.user)
```

The CreateOnlyDefault is used as the value for the unique_together validation on the model.

This was a breaking change in v3.8, required to allow correct behaviour elsewhere. (Previously read-only fields with a default were considered writable, with the default being used as the written value. Ultimately that turned out to be not a good idea.)
