### ISSUE TITLE
DestroyAPIView error when on_delete=models.PROTECT

### ISSUE THREAD

**Issue by MisakaDev** [encode/django-rest-framework#5958]
## Steps to reproduce
**models:**
```
class Region(models.Model):
    name = models.CharField(max_length=255)
    code = models.IntegerField()


class District(models.Model):
    region = models.ForeignKey('Region', related_name='districts', on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    code = models.IntegerField()
```

**views:**

```
class RegionDelete(generics.DestroyAPIView):
    queryset = Region.objects.all()
    serializer_class = RegionSerializer
```

## Expected behavior
HTTP code 423 or other.
Error detail.
## Actual behavior
Django exception

## Fix for me
**mixins:**
```
class DestroyModelMixin(object):
    """
    Destroy a model instance.
    """
    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        try:
            self.perform_destroy(instance)
        except django.db.models.deletion.ProtectedError as e:
            return Response(status=status.HTTP_423_LOCKED, data={'detail':str(e)})
        return Response(status=status.HTTP_204_NO_CONTENT)

    def perform_destroy(self, instance):
        instance.delete()
```

**Comment by tomchristie** [comment]
You’ll need to write a custom method to handle this case. I don’t think it’s common enough to warrant adding the extra complexity to the standard case.

**Comment by vaibhavhrt** [comment]
This can be fixed with just a couple of lines of code. Frameworks are supposed to make life easier so I think automatic exception handling for model delete should be added.

**Comment by jobec** [comment]
Old issue, but still oh so relevant.

From my point of view it's very common and serves as a crucial part to keep your database integrity.

**Comment by snowman2** [comment]
Running into this as well. Would be very nice to have this handled by default without a 500 error.

**Comment by Behoston** [comment]
> You’ll need to write a custom method to handle this case. I don’t think it’s common enough to warrant adding the extra complexity to the standard case.

xD, not common enough, sure, then throw 500 that is not a json but html. I hope you don't work on DRF anymore

**Comment by tomchristie** [comment]
Is anyone interested in submitting a pull request?

**Comment by vaibhavhrt** [comment]
Okay, I will open a PR soon.

**Comment by Behoston** [comment]
I've created my own error handler, I can upload gist, but I do not have
test for this and I think proper solution should be discussed with drf
maintainers/code owners. It will be a big change in api responses, so many
applications may already handling crapy 500 status code. This is an
acceptable answer to why it is not fixed yet.
In the other hand, error handling can be done much better. For now in DRF
we have only one error handler. Personally I'm using rollbar, that have own
error handler (just copy some stuff from request and call original drf
error handler). So, if I want to handle one more error, I need ensure that
I will call original error handler from drf or rollbar error handler before
or after I handle new error depending on settings (local env, demo or
prod). And selecting which handler should I call is done in my new handler,
not in settings. So, handling new errors and reusing handlers is nightmare.
It can be done like Middleware or at least using class instead of function.

czw., 3 lis 2022, 12:34 użytkownik Tom Christie ***@***.***>
napisał:
