### ISSUE TITLE
Auto refresh cache 

### ISSUE THREAD

**Issue by inspirassion** [encode/django-rest-framework#5986]
Why `django ` /  `Django-rest-framework` don't provide a way to automatically save and refresh caching api responses. I am working to define a logic that it can easily be automatised by the framework : 

- Save cache when apiview recieves a `GET`.
- Delete related cache when apiview recives `POST`, `PUT`, `PATCH` or` DELETE`.
- Consider related models in the step 2.

Are theire any plans to implement this in DRF in the future ?

**Comment by xordoquy** [comment]
Hi,
We don't have such plans because API may not be the only thing that alters the data, let alone data used across different entry points.
This being said, [we support, encourage and strongly favor the creation of Third Party Packages to encapsulate new behavior rather than adding additional functionality directly to Django REST Framework.](http://www.django-rest-framework.org/topics/third-party-packages/#about-third-party-packages)
