### ISSUE TITLE
Unauthorized message on immediate logout after login.

### ISSUE THREAD

**Issue by Sahil624** [encode/django-rest-framework#6052]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

When a user logouts immediately after logging in (requests for data are pending) It shows unauthorized . I happens because data request are made after token is destroyed. I think there should be some case for handling this scenario.

## Steps to reproduce
Login to API (I used Angular 4  as front end) and logout immediately . Logout before data requests are not completed.

## Expected behavior
It should log out without any error,

## Actual behavior
A "Unauthorized " message is returned.

**Comment by rpkilby** [comment]
Hi @Sahil624. The `rest_framework.authtoken` app only includes a [view for generating tokens](http://www.django-rest-framework.org/api-guide/authentication/#by-exposing-an-api-endpoint). If these tokens are being destroyed, this is either due to your application's code, or code that's been provided by a 3rd-party app. If you want to alter how tokens are destroyed, you should modify that code.

Alternatively, your client code should gracefully handle the `401 Unauthorized` responses. If the user has logged out, they shouldn't be viewing the originally requested data anyway.
