### ISSUE TITLE
Django Reset Serializer loses a file

### ISSUE THREAD

**Issue by Przemek625** [encode/django-rest-framework#6352]
I have a Simple serializer.

```
class MySerializer(serializers.Serializer):
    file = serializers.FileField()

```
I use this serializser in my view:

```
class MyView(APIView):

    permission_classes = ()
    parser_classes = (MultiPartParser,)

    def post(self, request):
        print(request.data)
        # <QueryDict: {'file': [<InMemoryUploadedFile: some_file.png (image/png)>]}>
        serializer = MySerializer(data=request.data)
        serializer.is_valid()

        print(serializer.data)
        # {'file': None}
```
I pass data to serializer, which containts file. After checking `serializer.data` it says that file is `None`.

What is more If I change the `serializer.is_valid()` line to `serializer.is_valid(raise_exception=True)` The view will return message that data are invalid.

```
{
  "file": [
    "This field can not be null."
  ]
}
```
This behaviour is strange to my. The docs says that request.data contains both file and non-file object. We can even see that in my print. The question is why my serialzier can't make use of it? Thie file magically disappears

**Comment by xordoquy** [comment]
For one thing, there's no reason the code provided would no lead to an invalid payload.
Next is you won't find the file within the `serializer.data` because this part is expected to be the response. By default it'll be an URL which you didn't set in the provided example.
Add the `use_url=False` to the `FileField` and thing will be different.
