### ISSUE TITLE
request.data is empty on create, update when using custom json parser

### ISSUE THREAD

**Issue by radzhome** [encode/django-rest-framework#6393]
## Checklist

- [ X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

See https://github.com/radzhome/drfcustomparser for code example and steps to reproduce

## Expected behavior

request.data should be filled along with request.body on create, update

## Actual behavior

request.data is blank on create, update when using original parser (or any custom parser) from a different location is used.

**Comment by tomchristie** [comment]
This issue boils down to "`DEFAULT_PARSER_CLASSES` doesn't work", which seems infeasible given that it's core functionality that's been there since forever, and we don't have a huge stack of failing tests, and other reporters raising the issue.

Strongly seems like something *else* is being misconfigured or misinterpreted here, but it's not super obvious to me what. I'd suggest that you'll want to try to simplify the issue further. (Eg. from a clean install of REST framework, with no models or anything else just create a plain old view and configure a custom parser class.)

If you can *still* demonstrate an issue at that point then I'd be happy to reopen this and try to look into things further for you.

**Comment by radzhome** [comment]
I thought that was a very simple example. I mean I would like to use my parser with a model but sure I'll simplify the example more.

**Comment by tomchristie** [comment]
Your parser implementation is what's at issue here...

In your example `decoded_stream` is not the decoded bytes, but a `StreamReader` instance, like: `<encodings.utf_8.StreamReader object at 0x10d8a65c0>`

Then `ujson` loads that, but because it's not as robust as the standard library `json` implementation, it's not raising an error to you that it's trying to decode an invalid type, and is instead just returning a plain empty dictionary to you.

**Comment by tomchristie** [comment]
Ah, no, to be more specific:

`decoded_stream` is a bytestream. In REST framework we pass it to `json.load` which accepts a bytestream. In your example you're passing it to `usjon.load` which apprarently doesn't handle it in the same way, and just returns an empty dictionary.

Try `decoded_stream.read()` or something along those lines.

**Comment by tomchristie** [comment]
Well. 3x faster at doing something that won't remotely be the bottleneck. With less well-defined behavior.
