### ISSUE TITLE
Multiple databases support

### ISSUE THREAD

**Issue by bgrzys** [encode/django-rest-framework#65]
It'd be nice to have multi databases support (https://docs.djangoproject.com/en/dev/topics/db/multi-db/)

**Comment by husainp** [comment]
Hi,
I am dealing with multiple dbs through manual switching using functions like "using(alias)" and switch_db(alias). But when serializer.is_valid() is called it always goes for validation into default database. How to take care of that.

You can find detailed explanation of issue which I am facing on stackoverflow.
Link:  http://stackoverflow.com/questions/42412218/while-using-django-restframework-multiple-database-serializer-is-valid-always

I an stuch at this point. Can u please help me out.

**Comment by xordoquy** [comment]
@husainp The serializers you are using aren't even those from DRF (from rest_framework_mongoengine.serializers import DocumentSerializer) so I'd suggest you bring this issue to the rest framework mongoengine project.

**Comment by husainp** [comment]
Thanks for your quick reply. I will raise issue under  rest framework mongoengine project.
Link: https://github.com/umutbozkurt/django-rest-framework-mongoengine/issues/209

Please let me know if someone has resolved such issue.

**Comment by husainp** [comment]
@xordoquy 
Can I use django-mongodb-engine as database backend and model and modelserializer instead of document and document serializer.

i.e If  I start using django-mongodb-engine instead of mongoengine and rest-framework-mongoengine, will that can have any problems.

Because I have checked following things with django-mongodb-engine + Model.model + Modelserializer and Mongodb as database.

1) Database routers for database switching.
2) Embedded Model field
3) DictField
4) Custom user

and things are working really nice

So if I migrate my project to models from documents, will that can stop me anywhere in future. Are there any limitations of  django-mongodb-engine ??? (Since django-mongodb-engine project's been dead for 2 years, or even longer)

**Comment by xordoquy** [comment]
@husainp I have no idea about any mongo thing and this is out of topic here as we don't support it. I'm confident you'll find your question answered on the Django user mailing list.

**Comment by MohammedBajuaifer** [comment]
@xordoquy I'm trying to do the same thing without using any other libraries but the is_valid() method keeps pointing to the default db.

**Comment by auvipy** [comment]
related https://github.com/encode/django-rest-framework/discussions/7921#discussion-3318109
