### ISSUE TITLE
I use throttle_classes at the api_view and after the limit time the program return to me Method Not Allowed: /api/xxx

### ISSUE THREAD

**Issue by wxy929629** [encode/django-rest-framework#6531]
my code is like this:

@api_view(['POST'])
@throttle_classes([OncePerFiveSecondsTrottle, ])
def send_msg_api(request):
    if request.method == 'POST':
        // todo..

And i use postman to post some data like this:
![image](https://user-images.githubusercontent.com/27196120/54977998-f0534f80-4fd9-11e9-9d0a-d3a8033a171f.png)

and the limit return like this:
![image](https://user-images.githubusercontent.com/27196120/54978016-fba67b00-4fd9-11e9-9694-f1747a7d04d6.png)

but after the limit time, it returns error and not display the Method
![image](https://user-images.githubusercontent.com/27196120/54978039-0cef8780-4fda-11e9-9ee0-16aeb84010d4.png)

Django returns:
Method Not Allowed: /api/submit_msg

 i use form-data to post, it runs well but x-www-form-urlencoded is not.

ps:
class OncePerFiveSecondsTrottle(AnonRateThrottle):
    rate = 1/s

djangorestframework   3.9.2

**Comment by xordoquy** [comment]
We do have a working [test case](https://github.com/encode/django-rest-framework/blob/c686749eef8afb6943f0d412d253c477d7c8e10f/tests/test_throttling.py#L86-L101) that shows otherwise.
I'm closing this issue because it isn't actionnable in its current form.
Will reopen if a minimal failing test case is added. Try to reduce your issue to the smallest failing code possible to track where the issue can be.
Otherwise, the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to get support.
