### ISSUE TITLE
ModelViewSet PUT and PATCH should just work

### ISSUE THREAD

**Issue by HashRocketSyntax** [encode/django-rest-framework#6663]
With this view in place I can create, read, list, and delete resources. Why can't I PUT and PATCH?
```
class SnippetViewSet(viewsets.ModelViewSet):
    serializer_class = SnippetSerializer
    queryset = Snippet.objects.all()
```
It's a StackOverflow nightmare looking at the different ways people are handling `.partial_update()` for the past few years.

---

Here I am trying to update the code field.

![image](https://user-images.githubusercontent.com/16389820/57493799-7e3a7f80-7294-11e9-9325-4580d3241327.png)

Also, why is PATCH returning 200 when nothing was PATCH'ed?

**Comment by rpkilby** [comment]
Hi @HashRocketSyntax. When updating resources, you provide data as part of the request body, not the query params.

> why is PATCH returning 200 when nothing was PATCH'ed?

The server is responding with a 200 because your PATCH request is essentially telling it to update the resource with nothing, which it did successfully. The server successfully did nothing.

**Comment by HashRocketSyntax** [comment]
@rpkilby thank you! people of the future internet. check out this image.
![image](https://user-images.githubusercontent.com/16389820/57557397-fca42980-7347-11e9-9e8d-a30df47573ff.png)
