### ISSUE TITLE
国外文凭办理精英国际文凭俱乐部www.diplomaclub.net

### ISSUE THREAD

**Issue by dferteyfbxcrterg** [encode/django-rest-framework#6788]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Actual behavior
[国外文凭办理](www.diplomaclub.net)精英国际文凭俱乐部[www.diplomaclub.net](www.diplomaclub.net)

**Comment by tomchristie** [comment]
Thanks @xordoquy 

I've blocked the account. I think it's probably a good idea for us to block spam bots, since it's more likely that it'll help @github internally flag them up as spam.

"New account. Creates Issue. Immediately blocked." Is a pretty good first-pass heuristic, and I assume they must have some various similar to that in place.
