### ISSUE TITLE
How to translate serializer field names

### ISSUE THREAD

**Issue by oussama-he** [encode/django-rest-framework#6978]
I'm building an app using Django, DRF, and VueJS. I have a serializer like this:

```python
class ArchivedBookListSerializer(ModelSerializer):
    class Meta:
        model = Book
        fields = ['title', 'author', 'nbr_pages', 'volumes', 'url']
```

I want to change field names to Arabic names so I can display them in the app with these Arabic names.
How can I do this?
Thank you in advance.

**Comment by rpkilby** [comment]
Hi @oussama-he. Field names should not be translated. For example, imagine that your Vue app renders a book object to a template `<h1 v-text="book.title"></h1>`. If you were to translate the field name, the template would break since the field name has changed. 

What you need instead is a mapping of translatable display names for each of the fields. However, that's outside of the scope of this discussion. I would look into plugins like [vue-i18n](https://kazupon.github.io/vue-i18n/) or [vue-gettext](https://github.com/Polyconseil/vue-gettext).
