### ISSUE TITLE
bad_request function is receiving parameters and not using them for anything

### ISSUE THREAD

**Issue by suelliton** [encode/django-rest-framework#7072]
**package**: rest_framework.exceptions
**bad_requests** function is getting an exception and does nothing with it, should return a string with the error

**Comment by tomchristie** [comment]
Thanks for raising this!

We're implementing the same interface as https://docs.djangoproject.com/en/dev/ref/views/#django.views.defaults.bad_request in order to allow Django's default exception handling to be switched out for a more API friendly style there.

I'd prefer us not to use the exception in the return response, as we *generally* don't want to mirror  information back to the user here, for the same reasons given in the Django docs...

>  By default, nothing related to the exception that triggered the view is passed to the template context, as the exception message might contain sensitive information like filesystem paths.
