### ISSUE TITLE
3.11 release notes not compiled

### ISSUE THREAD

**Issue by rpkilby** [encode/django-rest-framework#7154]
3.11 had an announcement, but the individual changes were not added to the release notes.

**Comment by Pomax** [comment]
This has been sitting for a month, and the longer it sits, the more important it becomes due to automated dependency checking. Dependency tooling pulls changelogs and release notes in order to inform maintainers what changed, not just the bug fixes but also the compatibility breaking changes and CVE notices. Without release notes for a large dependency, a release effectively hasn't happened yet =)

Can someone please take the time to update the site with the proper release notes? Especially because until that happens, new work will never even make it into larger projects that rely on DRF for API work, because it'll stay pegged to 3.10 until there's disclosure on what changes got introduced.

**Comment by Pomax** [comment]
fantastic, thanks @tomchristie!
