### ISSUE TITLE
Feature request: support for Django 3.1's async views

### ISSUE THREAD

**Issue by seanfarley** [encode/django-rest-framework#7240]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
This is a feature request for supporting the upcoming feature of Django 3.1 for async views.

## Expected behavior
Not through an assertion.

## Actual behavior
Assertion is thrown (understandably): ``Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'coroutine'>``

**Comment by Skorpyon** [comment]
I feel that async support require deed refactoring of all codebase. Probably you should try Aiohttp.

**Comment by xordoquy** [comment]
A failing test case would be a good start point.

**Comment by carltongibson** [comment]
> Steps to reproduce

Sorry, but can you actually provide a reproduce here. There's no reason DRF's views won't work perfectly well with Django 3.1 (albeit in a thread-pool executor **if** you're operating down the new Async pathway). 

So what have you done here? Defined an `async def` function then called it (to get a coroutine) rather than awaited it, using an async hander? — But that's not going to be a supported use-case. 

Maybe there's an issue here. Definitely "We want async views! 💃" is a valid request, although maybe a little previous — what use-case are you needing to satisfy? — but without more detail, this isn't an addressable issue.

**Comment by tomchristie** [comment]
Heya,

Let's all take a constructive tack to this, eh? I can see why the issue'd get closed down because it's framed in such a broad way that it's not clear what's been tried, what the expectations are, and what does or doesn't work.

The example from @seanfarley's repo has a narrower example...

```python
@api_view(['GET'])
async def book_api_view(request):
    books = Book.objects.all()
    serializer = BookSerializer(books, many=True)
    return Response(serializer.data)
```

As it happens, that isn't super useful, since we're declaring an async view, but making regular sync database operations within it, however it at least helps narrow down specifically *which* parts of REST framework we might want to adapt some support for.

An issue framed much more narrowly as "Support async views with `@api_view`" probably makes sense as a reasonable starting point here, right?

**Comment by tomchristie** [comment]
I've opened https://github.com/encode/django-rest-framework/issues/7260 for discussion on how & where we might start to support Django 3.1's async views.

**Comment by Skorpyon** [comment]
> @seanfarley don't use drf, use aiohttp (read: fuck off this isn't welcomed)

Easy, man. I not toxic and I really suggested you best solution, because I worked a lot with async python. It have some another paradigm and I sure that async django will surprise you with blocking, unexpected fails, stuck treads etc. So my strong opinion that if you need async python web framework Django is bad choice. Especially with ASGI that half slower than WSGI.

**Comment by tomchristie** [comment]
Locking this for now.

We've got #7260 for any constructive input on moving forward with initial elements of async support. 👍💛
