### ISSUE TITLE
Provide a setting to use HttpOnly cookie for Token Authorization

### ISSUE THREAD

**Issue by advename** [encode/django-rest-framework#7273]
Many online discussion exist about where to store the token for Token Authorization in web applications, after the intial Token Authentication.

The three main suggestions are:
- localStorage
- sessionStorage
- Cookies with HttpOnly (not accessible with client side JavaScript)

The first two are prone to XSS attacks.
The last one to CSRF attacks.

Good security is to store the token in a Cookie with HttpOnly and validate it from here on. CSRF token should then be passed during token authentication back to the user to be stored in localStorage/sessionStorage.

In future token authorization, the user passes the CSRF token in the request Header and Django automatically checks for the user token in the cookie.

**Comment by markopy** [comment]
How is this different from session authentication which makes the session cookie HttpOnly and the CSRF token is passed as header field by the client?

**Comment by advename** [comment]
Session cookie are locked to one domain, but if you're working cross domain (even a subdomain <-> are considered cross domain) then session won't work.

That's why we have Tokens and other authentication/authorization methods to handle this.
Many REST API with web applications use tokens/JWT to verify and authorize a user.
If REST Framework creates it's own token system, then consider using a more secure approach.

**Currently**, Token Auhtorization flow is that the token is returned to the client, the client has to store this token somewhere - and 70% of the time developers will simply dump it in local storage or session storage. Then in a new POST request, the client takes the token, places it in the `Authorize` header and voila - you are in.

But as i mentioned before, local & session storage are vulnerable to XSS attacks, and XSS attacks are more severe than CSRF attacks.

**Comment by markopy** [comment]
I don't understand what you are proposing. Sessions cookies are tied to domains because that's how cookies work, for good reason. Putting some other token into a cookie will be limited in exactly the same way.

I agree that storing part of the credentials in a cookie is better than just having a single token in local storage but that brings with it all the cross domain limitations cookies have.

**Comment by advename** [comment]
> I agree that storing part of the credentials in a cookie is better than just having a single token in local storage but that brings with it all the cross domain limitations cookies have.

If you set the correct CORS header, you can store Cookies on cross domains.
See this StackOverflow Answer: https://stackoverflow.com/a/25861695/3673659

Now, I'm talking here in context of DRF with websites/ web application and not Session Authentication but Token Authentication. The tokens are send in the body and the client needs to store them either in local storage or session storage.

A better solution would be to send them in HttpOnly cookies and also validate them using HttpOnly cookies

**Comment by tomchristie** [comment]
So, the best way to make any progress here would be to take ownership of it yourself, and create a custom auth class that implements the behaviour you'd like to see here.

You'd then be able to release this as a third party package, and we'd link to it from the main docs.

**Comment by markopy** [comment]
Just for completeness sake, it's entirely possible to use session authentication with DRF. You can set `SESSION_COOKIE_HTTPONLY = True` and use https://github.com/adamchainz/django-cors-headers to set the appropriate CORS headers on the server.
On the client you then have to simply include the CSRF cookie value in each request as a HTTP header. See django docs for details: https://docs.djangoproject.com/en/3.0/ref/csrf/#ajax

If you don't like the CSRF token being in a cookie you can easily disable it and make your own endpoint which hands it to your client. Since that is perhaps half a dozen lines of code I doubt it warrants it's own package.

**Comment by advename** [comment]
@tomchristie I have to be honest - I've only started Django like a month ago and am not suitable for creating a Python middleware that is about security. However, If some people could chip in contributing would I be up for it.

@markopy I thought so too - but after a couple of hours testing with that setting, the cookie was never available to cross domains.

On the other hand, I created a custom example project where i tried to implement these features on my own - but most definitely not good tho. https://github.com/advename/DRF-Token-Example/tree/master
I've tried to write a detailed readme with my ideas.

**Comment by markopy** [comment]
@advename I had a brief look at your code and I'm fairly sure you are just reimplementing session authentication by using the token as session id. I recommend you go back and try to get django's built in sessions to work.

Keep in mind that browsers have particular and differing behavior when it comes to cookies set against localhost. Set up some domains in your hosts file pointing to 127.0.0.1 to test properly.

**Comment by advename** [comment]
> Keep in mind that browsers have particular and differing behavior when it comes to cookies set against localhost. Set up some domains in your hosts file pointing to 127.0.0.1 to test properly.

Whoaw whoaw whoaw... how did this happen. 

I've been trying for at least two weeks now to implement authentication in DRF and had major issues with cookies not beeing set - until i switched from Firefox to Chrome! WHAT the heck? Why does Firefox not set cookies when the API server is on 127.0.0.1 ?

**Comment by markopy** [comment]
Have a look at CSRF_USE_SESSIONS if you don't want the CSRF cookie. I haven't used this myself but it seems to allow storing the CSRF value in the databased instead of a cookie.

Firefox does support setting cookies against localhost in general. Another thing to consider though is that if you are serving both the django backend and your front end from localhost on different ports they might have cookie name collisions since cookies are not separated by port.

**Comment by gustavosoeiro** [comment]
@advename Did you have success with this? I saw your git repo but it is untouched...
Please let know, yes?
