### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by justindhoffman** [encode/django-rest-framework#7317]
As far as I can tell the pip release 3.11.0 is quite far behind master and the documentation on the website. Can a new release be pushed forward? Or am I missing something?

**Comment by carltongibson** [comment]
The docs are for 3.11. We’re preparing 3.12 now. It’s been somewhat delayed by the pandemic. It’ll come.

**Comment by carltongibson** [comment]
In fact, that’s not true. Looks like the docs have been deployed since 3.11, including unreleased changes. Not sure what happened there... @tomchristie?

**Comment by tomchristie** [comment]
> Looks like the docs have been deployed since 3.11

There was a docs build on 4th March, which looks like I did it because the release notes for 3.11 hadn't been included.  https://github.com/encode/django-rest-framework/pull/7214

Are there any obvious points where the docs are out of sync. We could potentially look at restoring them to their state the 3.11 release date, but it'd be a bit fiddly.

> Can a new release be pushed forward? Or am I missing something?

As @carltongibson say, it'll come soon enough. We're all dealing with a whole bunch of extra life stuff at the moment, and it's pushed everything back.

**Comment by carltongibson** [comment]
I suspect it’s just the schema docs. 

Branch off 3.11, cherry pick the necessaries, and deploy? 😬

**Comment by justindhoffman** [comment]
Totally understand. More just wanted it to make sense. THANKS for all your work with this!

**Comment by errrken** [comment]
Any update on this?

**Comment by tomchristie** [comment]
Soon.
