### ISSUE TITLE
empty fields with default values not returned after partial update

### ISSUE THREAD

**Issue by ozgurakcali** [encode/django-rest-framework#7454]
## Steps to reproduce

 - create a serializer with a field with default value set:

```
class MySerializer(serializers.ModelSerializer):
    field_with_default_value = serializers.ReadOnlyField(default='fixed_value')

```

 - send a patch request to related api endpoint

## Expected behavior

After the update is complete, **field_with_default_value** is returned in the response

## Actual behavior

Response has no field **field_with_default_value** 

I think is is caused by **get_default** method of **Field** class:

```
def get_default(self):
	if self.default is empty or getattr(self.root, 'partial', False):
		# No default, or this is a partial update.
		raise SkipField()
	if callable(self.default):
		if hasattr(self.default, 'set_context'):
			self.default.set_context(self)
		return self.default()
	return self.default
```

Here, if no value is set for a field, and the serializer is initialized with partial=True, the field is skipped. This is necessary while updating the object, but while serializing the object after update is complete, such field need to be included in the response.

**Comment by tbrknt** [comment]
Hello @ozgurakcali ,

I was also able to verify this one. The response actually does not contain that field. 

As far as I have checked, the main reason why it has not been included in the response is the `read_only` check in the following lines:
https://github.com/encode/django-rest-framework/blob/431f7dfa3dc108d449044a6c9eef715416d53059/rest_framework/serializers.py#L396-L400

It seemed intentional, but maybe the intention there was to change it for `get_initial` but not for the use case that you mentioned.
I found that this check has been introduced in this commit:
https://github.com/encode/django-rest-framework/commit/3e878a3207ba79785d41b4d6af5cd956156d45a3

I will check how the issue can be fixed without breaking other usages of `get_initial`.
