### ISSUE TITLE
NullBooleanField returns boolean value `False` for empty QueryDict.

### ISSUE THREAD

**Issue by cosmosgenius** [encode/django-rest-framework#7582]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create a serializer as below with the test data
```
from django.http import QueryDict
from rest_framework import serializers

class TestSerializer(serializers.Serializer):
    is_active = serializers.NullBooleanField(required=False)

s_dict = TestSerializer(data={})
s_dict.is_valid()

s_qdict = TestSerializer(data=QueryDict())
s_qdict.is_valid()
```

## Expected behavior
`s_dict` and `s_qdict` has the same value which is `is_active: None`

## Actual behavior
`s_dict` returns `is_active: None` but `s_qdict` returns `is_active: False`

`NullBooleanField` was primarily used to avoid `default_empty_html` from `BooleanField`. Now that it is merged what is the alternative?

**Comment by amikrop** [comment]
I observe that https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L432 is False for the first case ({}) which raises SkipField here https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L483 and True for the second case (QueryDict()) which lets set_value to be called here https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L486
That is the difference between those 2 cases, which causes this, but I don't know if this is intended behavior or not.

**Comment by xordoquy** [comment]
This is likely because `NullBooleanField` doesn't override the `BooleanField`'s `default_empty_html` value which is `False`.

If you alter your field definition as `is_active = serializers.NullBooleanField(required=False, default=None)` you'll get a consistent behaviour.

A PR with the appropriate test could fix that too.

**Comment by amikrop** [comment]
That's right, are we sure though that the developer's intentions are for `NullBooleanField`'s `default_empty_html` to be `None`?
If yes, we can make that small PR, should be trivial.

**Comment by cosmosgenius** [comment]
> That's right, are we sure though that the developers' intentions are for `NullBooleanField`'s `default_empty_html` to be `None`?
> If yes, we can make that small PR, should be trivial.

Yes that is the expectation. But @xordoquy alternate field definition works well with `BooleanField` which is the right way to do since `NullBooleanField` is deprecated.

This does feel like a breaking change though in my opinion. If we didn't have proper CI/CD tests, this won't have been caught.

**Comment by beesnotincluded** [comment]
We too were caught out by this change. Our CI/CD test noticed the regression and we spent quite a while getting to the bottom of it.

**Comment by jaredmcdonald** [comment]
Just ran across this when upgrading our project to to 3.12.x (from 3.11.x) and also only caught it because of tests.

A BooleanField with `default=None` is still a bit of a departure from the previous behavior, where e.g. in @cosmosgenius' example above, `is_active` would not be present in `validated_data` if it wasn't passed in at all in the QueryDict. Is there some reason that the key should be present?

**Comment by Safrone** [comment]
I faced this as well where I was expecting the empty query dict to not insert the boolean

seeing that NullBooleanField is deprecated for DRF and django and I didn't actually need the third state (just using it to know whether true or false was explicitly given since default_empty_html otherwise obfuscates that), my solution is to override BooleanField:

```
from rest_framework import fields, serializers

class DefaultEmptyBooleanField(fields.BooleanField):
  default_empty_html = fields.empty

class MySerializer(serializers.Serializer):
    boolean_field = DefaultEmptyBooleanField(required=False)
```
use case:

```
from django.http import QueryDict

serializer = MySerializer(data=QueryDict(''))
serializer.is_valid()
serializer.validated_data # OrderedDict()

serializer = MySerializer(data=QueryDict('boolean_field=true'))
serializer.is_valid()
serializer.validated_data # OrderedDict([('boolean_field', True)])
```

You can add `allow_null=True` to `DefaultEmptyBooleanField()` for the added explicitly handled option

**Comment by auvipy** [comment]
can any of you try https://github.com/encode/django-rest-framework/pull/8614 and report back please? seems related to this issue
