### ISSUE TITLE
about ListField

### ISSUE THREAD

**Issue by wlccgp3** [encode/django-rest-framework#7666]
AssertionError if i code this:
```
telephone_field = serializers.CharField()

class TelephoneListSerializer(serializers.Serializer):
    telephone = serializers.ListField(child=telephone_field, allow_empty=False)
    telephone2 = serializers.ListField(child=telephone_field, allow_empty=False)
 ```
https://github.com/encode/django-rest-framework/blob/bb133522efaf6ce3ae8fdf1dec6cd79566cfd166/rest_framework/fields.py#L1610

why not code this:
```
self.child = copy.deepcopy(kwargs.pop('child', self.child))
```

**Comment by seppeljordan** [comment]
I don't think that this would work. When looking at the code I noticed that in line https://github.com/encode/django-rest-framework/blob/bb133522efaf6ce3ae8fdf1dec6cd79566cfd166/rest_framework/fields.py#L1615 the `self.child.bind()` method is called. This method in turn sets the `source` attribute of `child`. It looks to me like there is currently now good way around this limitation.

I propose the following two options:

## Fix the client code from the OP in the following manner:
```
telephone_field = serializers.CharField

class TelephoneListSerializer(serializers.Serializer):
    telephone = serializers.ListField(child=telephone_field(), allow_empty=False)
    telephone2 = serializers.ListField(child=telephone_field(), allow_empty=False)
```

Notice the parenthesis are now around `telephone_field` instead of `serializers.Charfield`

## Deepcopy the `child` argument to `ListField`

https://github.com/encode/django-rest-framework/blob/bb133522efaf6ce3ae8fdf1dec6cd79566cfd166/rest_framework/fields.py#L1610 could be changed to
```
self.child = copy.deepcopy(kwargs.pop('child', self.child))
```

This would introduce an implicit requirement for all possible `child` arguments (and therefore serializers) that they should be able to be `deepcopy`-ed (speak: `__deepcopy__` must be implemented properly).
