### ISSUE TITLE
Message permission classes attribute not working

### ISSUE THREAD

**Issue by francosopo** [encode/django-rest-framework#7712]
Hi!
I'm using DRF 3.12.2 and I'm writting my own permission classes to override the default message that throws the exception when a user is attempting to use an authenticated endpoint. But following the documentation it just doesn't work.
## Steps to reproduce
class MyAuthenticationClass(BasePermission):
       message = "Use a token please"
       code= 403
     def has_permission(self, request, view):
          return request.user and request.user.is_authenticated
## Expected behavior
headers = {
    "Authorization": "Token "+token
}
resp = Client().get(url)
self.assertEqual("Use a token please", resp['message'])
## Actual behavior
Assertion error: "Use a token please" != "Authentication credentials were not provided."

**Comment by nathanglover** [comment]
Hey @francosopo the reason why you are seeing a different error message is because DRF is raising a ` NotAuthenticated` exception. This happens because DRF checks if the request is authenticated before checking permissions. This type of exception trumps any permission related exception as you can see from the permission_denied view within DRF.

```python
    def permission_denied(self, request, message=None, code=None):
        """
        If request is not permitted, determine what kind of exception to raise.
        """
        if request.authenticators and not request.successful_authenticator:
            raise exceptions.NotAuthenticated()  # <-- HERE
        raise exceptions.PermissionDenied(detail=message, code=code)
```
[rest_framework/views.py#L169](https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L169)

The actual message DRF is returning can be found here [rest_framework/exceptions.py#L173](https://github.com/nathanglover/django-rest-framework/blob/master/rest_framework/exceptions.py#L173).

It's not exactly clear what you are trying to do, but here are a few solutions:
1. To force users to use `TokenAuthentication` set the `DEFAULT_AUTHENTICATION_CLASSES` setting to `rest_framework.authentication.TokenAuthentication`. [docs](https://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme) 
2. If you are want to fix your test use either the `client.credentials(HTTP_AUTHORIZATION='Token ' + token.key)`  or `.client.force_authenticate(user=user)` methods. [docs](https://www.django-rest-framework.org/api-guide/testing/#credentialskwargs)
    - This authenticates the request, and returns the message associated with the Permission class if there is one. 
    - Here is an example using APIRequestFactory but it's the same idea with APIClient. 
     ```python
    import pytest
    from rest_framework import permissions, views, response
    from rest_framework.test import APIRequestFactory, force_authenticate
    
    
    class MyPermissionClass(permissions.BasePermission):
        message = "Some custom message"
        code = 403
    
        def has_permission(self, request, view):
            return False  # permission can't be granted for message to be returned
    
    
    class MyView(views.APIView):
        permission_classes = [MyPermissionClass]
    
        def get(self, request):
            return response.Response("Hello World")
    
    
    def test_MyAuthenticationClass(user):
        factory = APIRequestFactory()
        view = MyView.as_view()
        request = factory.get("/some-url")
        force_authenticate(request, user)  # drf checks if the request is authenticated first before the permissions. 
        response = view(request)
        assert response.data["detail"] == MyPermissionClass.message
        ```

3. To override the message returned when a request is not authenticated with Token Auth, I think you might need to subclass `TokenAuthentication` and override the `authenticate` method and then set you custom class as the first `DEFAULT_AUTHENTICATION_CLASSES` in the settings. [code](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py#L151) 

Hopefully that clears things up for you. Happy coding!

**Comment by nathanglover** [comment]
This should be closed now.
