### ISSUE TITLE
Nit: github release version and pypi release version mismatch

### ISSUE THREAD

**Issue by adamf** [encode/django-rest-framework#7731]
## Steps to reproduce
Look at https://pypi.org/project/djangorestframework/#history - latest is 3.12.2

Look at https://github.com/encode/django-rest-framework - latest is 3.9.3

<img width="1403" alt="Screen Shot 2021-02-26 at 9 46 45 AM" src="https://user-images.githubusercontent.com/188338/109335923-8b34b400-7817-11eb-8af8-001aaefe0958.png">

<img width="1336" alt="Screen Shot 2021-02-26 at 9 45 56 AM" src="https://user-images.githubusercontent.com/188338/109335892-81ab4c00-7817-11eb-9d26-c7645063836b.png">

# Expected behavior
Versions should match on github and pypi

## Actual behavior

Versions don't match.

**Comment by auvipy** [comment]
the last tag https://github.com/encode/django-rest-framework/releases/tag/3.12.2

**Comment by carltongibson** [comment]
GitHub releases are (for us) just an additional maintenance burden. I tried creating them for a while, but it's not worth it.

As for essentially all Python packages, PyPI is the canonical source. 


If somebody can create an Action to auto-create a release from a tag, pointing to the matching PyPI release then we can look at that, but otherwise this a `wontfix`.

**Comment by tomchristie** [comment]
Yes, I think in due course we'll sharpen up the release process for REST framework to occur via actions, as we have for other encode projects (which works really, really nicely). Until then the mismatch is a niggle we've just got to live with.
