### ISSUE TITLE
Allow csrf_exempt decorator

### ISSUE THREAD

**Issue by emperorcezar** [encode/django-rest-framework#799]
It appears that the session authentication always ignores a view being decorated as `csrf_exempt`.

When the middleware is called at https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authentication.py#L120 it doesn't pass the callback.

Not sure if its possible to pass the callback here.

**Comment by kvbik** [comment]
seems we could have a solution for this with @aleszoulek - someone against re-opening?

**Comment by xordoquy** [comment]
@kvbik can you provide a use case (not asking for code at this point) where you would use `SessionAuthentication` along with a `csrf_exempt` view.
I really can't see a use case with one won't want csrf check for a view.

**Comment by kvbik** [comment]
maybe you are right @xordoquy :)) here is our use case: we always disable `CSRF` for auth views (login/logout) because there is really no point of having it there and without `CSRF` you can for example cache better. you can set different auth classses for this specific view - this is what we do right now, but then you have to copy/paste the default auth classes you have in settings and replace the session one with the custom one. `csrf_exempt` seems like more django-ish approach (or "django-compatible" [tm]).

**Comment by xordoquy** [comment]
@kvbik I still don't see how this relate to DRF.
login / logout views are pure Django views. Therefor the issue with the SessionAuthentication doesn't apply since the latter is for API views only.

**Comment by aleszoulek** [comment]
I think the general issue here is that when you want to disable CSRF for a specific DRF view, you need to do both:
1) `csrf_excempt` decorator - to disable Django's middleware check (obvious)
2) Override authenticators for a view - to disable DRF check (hard to find and debug)

DRF should honor Django's way of disabling CSRF, so user (developer) doesn't have to take care of that twice and more importantly that there is one obvious way how to do so.

**Comment by kvbik** [comment]
@xordoquy i did not mean the `django.contrib.auth` ones, but when you have your custom views for that.

**Comment by tomchristie** [comment]
> DRF should honor Django's way of disabling CSRF

That's not possible - we need to @csrf_exempt by default in order to support both session and non-session auth styles.

> you need to do both

You need to do the second, only. Using a subclassed SessionAuthentication that does not enforce the CSRF check is sufficient.

**Comment by xordoquy** [comment]
@kvbik I don't think it's a good design to have the authentication done within the API.
If you are using JS, then the user can simply log in with a regular view and SessionAuthentication.
If it's an application then it can use token based auth.
We may add some notes in the documentation about it but to me it really sounds as a too specific edge case.

**Comment by kentor** [comment]
Use case: I have POST endpoint that just returns some cryptographically secure random bytes. Thing is this request in called in a web worker and I don't want to pass the csrf token to the web worker (one less thing to pass/worry about). The request doesn't touch modify data so it should be fine if csrf check is disabled.

**Comment by xordoquy** [comment]
If it's a web worker, it's outside the API so it's down to Django regular views restrictions.

**Comment by bf0** [comment]
I have to say, the say DRF integrates with django's csrf functionality is absolutely terrible.

**Comment by tomchristie** [comment]
@bf0 Care to elaborate in any useful way?

We enforce CSRF for session authentication (when you'd be doing it wrong if you didn't), and we disable CSRF for any other authentication schemes (when you don't want it).

If you've anything useful to add to how you believe the behavior should be different then please go ahead.

**Comment by bf0** [comment]
Apologies for the brash comment. My complaint is that it seems impossible to get a csrf token via DRF class based views. The @ensure_csrf_cookie decorator doesn't work with DRF class views. It just silently doesn't set the header. Further, the @csrf_exempt decorator brakes class based views. It will complain there is no method as_view(). Both behaviors are not graceful and there is nothing in the DRF documentation about either of these facts.

My solution is to not use class based views, which is too bad.

**Comment by xordoquy** [comment]
API will send the csrf cookie so there's no reason to enforce `ensure_csrf_cookie`. As for `csrf_exempt` I'd be interested in hearing what the use case is.

As for now, I've seen people removing it because it seems hard to send a cookie in their request. I don't want this to happen because it breaks security and Django has a very good documentation page about setting that cookie.

**Comment by tomchristie** [comment]
Seconding @xordoquy here.

If there is a valid use-case for a CRSF-exempt, session authenticated view, then that's still perfectly possible to handle. The right approach there is to subclass `SessionAuthentication` into a `CSRFExemptSessionAuthentication` and apply that to the view (rather than using a decorator.) 

(See the implementation here https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authentication.py#L110 )

**Comment by jamiecounsell** [comment]
@tomchristie I'm currently running into a similar issue and trying to decide what to do. I think I might have the use case you're talking about. I'm building a Cordova application with DRF and Django. Cordova's cookie support is trash and is magically working for some things but not CSRF. The API currently uses session auth, so I wanted to essentially provide another API for the mobile device that is CSRF exempt, since within my understanding, there are not CSRF risks on mobile.

My options are as follows:
- Subclass SessionAuthentication, but I can't find a way to do this and still define a view only once if it's used for web and mobile. I'd need to define each view, then a subclass of that view for the mobile API
- Embed a whole other set of URLs for mobile (like `/api/mobile` instead of `/api`), with the same API underneath but without CSRF protection. This works in combination with the previous point _or_ if `csrf_exempt` would work, which it won't because I'm using SessionAuthentication.
- Switch to localStorage, but this is a lot of manual work for something that previously has been handled by cookie magic and few lines of code in the angular app
- Switch to token auth, but again it's a lot of work for a simple problem.

Would love to get your input on this - I might be overlooking something entirely. The problem with your previous comment is that It's a lot of boilerplate to subclass every single view just to change the authentication classes.

**Comment by Pithikos** [comment]
This is still an issue and there's no clear solution to this without having to dig.

Use case; "Sign in with Google". I simply need to exchange a Token ID for a session ID in a view. No need for CSRF

**Comment by xordoquy** [comment]
> I simply need to exchange a Token ID for a session ID

Why would you have `SessionAuthentication` for that endpoint ?

**Comment by Pithikos** [comment]
> > I simply need to exchange a Token ID for a session ID
> 
> Why would you have `SessionAuthentication` for that endpoint ?

That is an implementation detail - sessions in my case are for both logged-in and anonymous users. Doing the initial exchange works fine. However that endpoint can be called a 2nd time afterwards once an authenticated session is established. Without the `csrf_exempt` working, I am unable to make it work as intended without digging into the authentication mechanics.

The main point is that there are valid edge cases where you need to bypass the CSRF.
