### ISSUE TITLE
null=True is not respected by AutoSchema when the field is on read_only_fields

### ISSUE THREAD

**Issue by canassa** [encode/django-rest-framework#8041]
Hello,

Take this ModelSerializer for example:

```python
class MyModel(models.Model):
    my_field = models.DateTimeField(null=True, blank=True)

class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = ["my_field"]
        read_only_fields = ["my_field"]
```

If you generate this serializer schema you will notice that the `null=True` was ignored by the generated schema

``` python
>>> inspector = AutoSchema()
>>> schema = inspector.map_serializer(MyModelSerializer())
>>> schema['properties']['my_field']

{'type': 'string', 'format': 'date-time', 'readOnly': True}
```

Removing the from the `read_only_fields` fixes the problem and the schema goes back to:

```python
{'type': 'string', 'format': 'date-time', 'nullable': True}
```

**Comment by kevin-brown** [comment]
In theory, this should produce both `readOnly = True` and `nullable = True`, which is allowed per the OpenAPI spec.

This is not happening because `null=True` on the model is translated to `allow_null=True` on the serializer field which is stripped out when `read_only=True` is specified.

https://github.com/encode/django-rest-framework/blob/24a938abaadd98b5482bec33defd285625842342/rest_framework/serializers.py#L1327-L1333

It's not entirely clear at first glance why `allow_null` is removed since there doesn't appear to be any assertions explaining why these two wouldn't be allowed at the same time. My only guess is because normally this only applies to handling `null` in input data, but we do have code which also uses this for null coercion in outgoing data as well.
