### ISSUE TITLE
request with .force_athenticate() still giving 401

### ISSUE THREAD

**Issue by Massakera** [encode/django-rest-framework#8359]
## Checklist

- [ ] Raised initially as discussion #...
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.

I've been trying to implement a test in a view where my permission_class is (IsAuthenticated) but when I use `force_authenticated(request,user=user)` it still gives me 401 unauthorized. My testcase:

    def test_final_result(self):
        user = User.objects.get(username='test1')
        story_id = Story.objects.get(storyName='testplanning').id
        room_id = PokerRoom.objects.get(name='planning').id
        request = self.client.post(reverse('finalvotes', kwargs={'pk': room_id, 'idStory': story_id}), {'finalResult': '2'}, format='json')
        force_authenticate(request, user=user)
        self.assertEqual(200,request.status_code)

**Comment by Smixi** [comment]
My guess is that you're trying to use the client request instead of the APIRequest factory. The client request behave as a web browser, so when you do 

```python
    request = self.client.post(reverse('finalvotes', kwargs={'pk': room_id, 'idStory': story_id}), {'finalResult': '2'}, format='json')
```

the request is performed, your view executed, and result is returned.

If you want to have a request object like in your view, you should use the ApiRequestFactory, not the ClientFactory or RequestsFactory.

This does works : 

Example : 

```python
from django.test import TestCase
from rest_framework.test import APIRequestFactory, force_authenticate, APIClient
from django.contrib.auth import get_user_model

User = get_user_model()

from testperms.views import UserView
# Create your tests here.
class SimpleTest(TestCase):
    def setUp(self):
        # Every test needs access to the request factory.
        self.factory = APIRequestFactory()
        self.client = APIClient()
        self.user = User.objects.create_user(
            username='jacob', email='jacob@…', password='top_secret')
    # Work
    def test_request_api_request(self):
        request = self.factory.get('/users')
        view = UserView.as_view({'get': 'list'})
        force_authenticate(request, user=self.user)
        response = view(request)

   # DOES NOT WORK
    def test_request_client(self):
        request = self.client.get('/users/')
        view = UserView.as_view({'get': 'list'})
        force_authenticate(request, user=self.user)
        response = view(request)
```

**Comment by Smixi** [comment]
@Massakera did it worked for you ?

**Comment by mschoettle** [comment]
In theory his `force_authenticate` should just be above `client.post`. However, I ran into the same (or similar) problem.

The following works until I added a middleware that checks whether `request.user.is_authenticated`.
Minimal working example (using `pytest`):

```python
from rest_framework.test import APIClient

def test_some_functionality(admin_user):
    api_client = APIClient()
    api_client.force_authenticate(user=admin_user)
    response = api_client.get('/api/some-api-path/'))

    assert response.status_code == 200
```

In the middleware `request.user` returns `AnonymousUser`. Is this a bug or am I doing something wrong?

**Comment by Smixi** [comment]
Both should work for your purposes, can you share your code if you think it's force_authenticate is buggy ?

**Comment by Massakera** [comment]
Sorry for delaying the answer! Both solutions did it worked for my code and It was my mistake

**Comment by mschoettle** [comment]
> Both should work for your purposes, can you share your code if you think it's force_authenticate is buggy ?

I looked into it further: I had added a middleware (login required middleware) that checks `request.user.is_authenticated`. Using `force_login` it returns `True`, with `force_authenticate` it returns False.

I also observed that using `SessionAuthentication` `request.user` returns the actual user whereas when using `TokenAuthentication` it always returns `AnonymousUser`. After thinking about it it does make sense (since my understanding is that DRF is not providing an auth backend for token authentication, correct me if I am wrong). At the very least the [documentation](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) is misleading since it says that `request.user` will be a Django `User` instance.
