### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by robd003** [encode/django-rest-framework#8496]
Django 4.1 alpha1 was just released and now [supports async ClassBasedViews](https://docs.djangoproject.com/en/dev/releases/4.1/#asynchronous-handlers-for-class-based-views)

Could we get DRF APIViews to support async since it's already available in the master branch of Django?

**Comment by sun337** [comment]
This is much needed.

**Comment by TheWeirdDev** [comment]
Are there any plans to implement this?

**Comment by PaoloC68** [comment]
well, honestly I cannot imagine has the whole DRF can be future-proof without adding a fully fledged async support.

**Comment by robd003** [comment]
@tomchristie any chance this could get put on the roadmap?

**Comment by firminoneto11** [comment]
Up

**Comment by hguitar** [comment]
DRF async support would much appreciated!

**Comment by helenap** [comment]
I have an API that depends on a third party https call and this will really make my life better, when can this be out?

**Comment by em1208** [comment]
@tomchristie I would like to work on this!

**Comment by tomchristie** [comment]
Noted. I expect that a third-party package implementing an `AsyncAPIView` would be a good start here.

Has anyone attempted an implementation of an equivalent to the existing APIView? What blockers are there to being able to implement one? What particular support is needed from the maintenance team here?

**Comment by em1208** [comment]
I haven't tried before but I would like to start with a test implementation. I will report any blockers. When would you like to review a PR for DRF?

**Comment by em1208** [comment]
I opened this PR https://github.com/encode/django-rest-framework/pull/8617 with a tentative implementation of the async support.

**Comment by robd003** [comment]
You rock @em1208

**Comment by tomchristie** [comment]
Okay, so @em1208 has a neatly done pull request which adds async view support.

My concerns around this are to do with introducing false expectations to our users. I'd rather explore that through conversation instead of dictating, so here goes...

Could somebody start by giving an example of what you want this support for and why?

**Comment by em1208** [comment]
As an extension of my PR, I think it would be good to have separate async mixins using the new async API of the queryset and it should be enough for most users.

**Comment by firminoneto11** [comment]
With async support from DRF users would be able to fully go async for their apis, allowing them to use awsome tools such as httpx, async db drivers in the future and also use the new queryset api that Django's team is working on, without much effort, by just creating a regular async DRF view.

I also think that going full async with new DRF's views could improve even more concurrency on apis, because we would be able to write non blocking code, which is amazing!

**Comment by em1208** [comment]
I can update the PR to make it ""async all-the-way" if it would make it acceptable, I tried to minimise the impact on the existing codebase. I understand the preference is for a third party package but I still think the new async functionality of Django could be nicely supported by DRF together with the existing functionality.

**Comment by em1208** [comment]
Thanks @tomchristie for taking this into consideration. I updated the PR https://github.com/encode/django-rest-framework/pull/8617 to have an async dispatch method.

**Comment by Archmonger** [comment]
I would disagree with an `AsyncAPIView` class. The best approach probably involves mimicking what Django Core is doing. 

That is, dynamically deciding whether to dispatch as `async` or `sync` based on whether [all HTTP method functions are `async`](https://github.com/django/django/blob/9942f3fb490f56bf28ee69f0a07f3eb62e7d3ab3/django/views/generic/base.py#L63).

**Comment by em1208** [comment]
@Archmonger thanks for your comment. I remove the `AsyncAPIView` and done all the changes under `APIView `.

**Comment by tomchristie** [comment]
So https://github.com/em1208/adrf is looking great.
I'm wondering where the best place to link to this from the docs would be?
Perhaps n "Async Views" section in https://www.django-rest-framework.org/api-guide/views/ noting that support for those is provided by this third party package?

**Comment by smittysmee** [comment]
What is the status of this?

**Comment by tomchristie** [comment]
It looks to me like it's awaiting on a documentation pull request.

An "Async Views" section in https://www.django-rest-framework.org/api-guide/views/ linking to the `adrf` package would make sense.

**Comment by tomchristie** [comment]
I'd still agree with my comment above... I'd suggest that someone opens a pull request adding `adrf` to the documentation, as this will help improve its visibility.

**Comment by johnthagen** [comment]
I'm curious the reason not to pull `adrf` fully into DRF if it is the solution?

**Comment by tomchristie** [comment]
> I'm curious the reason not to pull adrf fully into DRF if it is the solution?

If we're going to add complexity to a codebase, then we need to be confident that it's worth the trade-off.
Dealing with that as a third party package is a more flexible way to explore the design space, without committing ourselves to it.

**Comment by errrken** [comment]
> 



> > I can update the PR to make it ""async all-the-way" if it would make it acceptable
> 
> It'd certainly be interesting to know what that'd look like. (It's still very likely I'd prefer to see work there in a third party package, but.)
> 
> The sync-to-async wrapper makes it really nice and easy, but we're also essentially indulging in false advertising. Async in that case isn't going to improve overall request/response concurrency at all, and really only _potentially_ helps in exceedingly narrow use-cases such as "we need a view that makes two outgoing HTTP requests in parallel".

@tomchristie Could you please elaborate on why it would only _potentially_ improve concurrency when running multiple outgoing long-running HTTP requests? I've seen you really try underline that you do not want to offer any false expectations and false marketing here in this thread (which makes sense!), but in this particular scenario I am curious if you could explain more? This is purely the only reason I want to add async behavivour to some(!) of our views

**Comment by HMaker** [comment]
> > 
> 
> > > I can update the PR to make it ""async all-the-way" if it would make it acceptable
> > 
> > 
> > It'd certainly be interesting to know what that'd look like. (It's still very likely I'd prefer to see work there in a third party package, but.)
> > The sync-to-async wrapper makes it really nice and easy, but we're also essentially indulging in false advertising. Async in that case isn't going to improve overall request/response concurrency at all, and really only _potentially_ helps in exceedingly narrow use-cases such as "we need a view that makes two outgoing HTTP requests in parallel".
> 
> @tomchristie Could you please elaborate on why it would only _potentially_ improve concurrency when running multiple outgoing long-running HTTP requests? I've seen you really try to underline that you do not want to offer any false expectations and false marketing here in this thread (which makes sense!), but in this particular scenario I am curious if you could explain more? This is purely the only reason I want to add async behaviour to some(!) of our views

Async IO code doesn't necessarily speeds up your code, it just reduces the server resources usage for concurrent tasks by leveraging concurrent network IO in a single-threaded application.

**Comment by medihack** [comment]
Bump. I think it would be nice to leave this issue open as long as adrf is evaluated (and maybe will be integrated in DRF itself).

**Comment by PythonCoderAS** [comment]
Along with Django 4.2, ADRF is missing async Serializer support, and now that the ORM supports async it should be easier to implement.

**Comment by ColemanDunn** [comment]
> Along with Django 4.2, ADRF is missing async Serializer support, and now that the ORM supports async it should be easier to implement.

It seems like async serializers were added in [this commit](https://github.com/em1208/adrf/commit/c661151a5d57224032e1e7b03aa5826816fe2965) about a month before you commented no?

**Comment by PythonCoderAS** [comment]
I didn't see it in the latest stable version so I assumed it wasn't done yet, my bad.

**Comment by auvipy** [comment]
this functionalities will be handled with extensions.

**Comment by tomchristie** [comment]
Closing this issue now. Perfectly happy to recommend `adrf` in the same way as any of our other third party extensions.

**Comment by Ou7law007** [comment]
Is this something to reconsider in 2026?

**Comment by Natgho** [comment]
> Is this something to reconsider in 2026?

As far as I can tell, ADRF is still being actively developed and maintained. Is there a specific area where there are shortcomings?

**Comment by Ou7law007** [comment]
> > Is this something to reconsider in 2026?
> 
> As far as I can tell, ADRF is still being actively developed and maintained. Is there a specific area where there are shortcomings?

Thanks for the quick response 😄.

I'm not sure about "being actively developed" when it's been in beta for years (currently v0.1.12). Also having a 3rd party dependency specifically and solely to support asnyc in another 3rd party dependency can create extra dependency and maintenance issues, but either way regardless of ADRF.

The valid reason I read back then was by @auvipy from Nov 27, 2022 https://github.com/encode/django-rest-framework/pull/8617#issuecomment-1328215841

> IMHO, **async support in django is not yet a first class/complete from developers and technical points of view**. so we should still wait for further django releases and try async drf as a 3rd party extension for some time.

I think django has now improved well enough for the above mentioned reason to at least not be as valid as it was back then anymore. That's why I'm asking if it's now time that django is no longer "not a first class/complete" anymore. If that's the case, then maybe it's worth reconsidering again.

Python has also had a big leap in terms of support for async since 2022.

So things have absolutely changed, that now it's at least worth reconsidering.

What exactly is preventing DRF from supporting async out of the box? I'm curious.

**Comment by browniebroke** [comment]
> I'm not sure about "being actively developed" when it's been in beta for years (currently v0.1.12)

Is it in beta because of the zero-ver or something else? FastAPI has been on version zero for years as well...

> Also having a 3rd party dependency specifically and solely to support asnyc in another 3rd party dependency can create extra dependency and maintenance issues, but either way regardless of ADRF.

We're all unpaid volunteers on here as well, and we can barely keep up with the current volume of changes (which isn't very big). Adding async support if not something we'll have the capacity to do in the foreseeable future.

> I think django has now improved well enough for the above mentioned reason to at least not be as valid as it was back then anymore. That's why I'm asking if it's now time that django is no longer "not a first class/complete" anymore.

Sure, it made some progress, but I also remeber this discussion from the forum: [Is DEP009 (“async-capable Django”) still relevant?](https://forum.djangoproject.com/t/is-dep009-async-capable-django-still-relevant/30132)

> What exactly is preventing DRF from supporting async out of the box? I'm curious.

Volunteer time mainly. 

Let me revert this question: what prevetns you/folks from investing their energy into ADRF? What can't be done in ADRF that would justify doing in DRF?

Tengential, but there are discussion ongoing to think about [the REST story for Django ](https://forum.djangoproject.com/t/django-needs-a-rest-story/42814) (taking a step back from DRF), which touches on your first point with 3rd party packages: if you want to do an API with Django, you need a 3rd party package (DRF, django-ninja). Sure you could hand-roll it, but in practice it's not very common.

Yes, it's 2026, but the answer is still no, as it's not a question of dates.

**Comment by Ou7law007** [comment]
@browniebroke Are you having a bad day or something? I asked a fully valid **TECHNICAL** question, there's no reason to get angry!

You can get mad about it as much as you want, but being an "unpaid volunteer" is not a valid **TECHNICAL** reason.

We're all "unpaid volunteers" in different projects in the wild.

Have a nice weekend.

**Comment by alexandernst** [comment]
@browniebroke If somebody steps up and creates a PR integrating adrf, would you be willing to accept it?

**Comment by browniebroke** [comment]
> Are you having a bad day or something? I asked a fully valid **TECHNICAL** question, there's no reason to get angry!
> 
> You can get mad about it as much as you want, but being an "unpaid volunteer" is not a valid **TECHNICAL** reason.

I'm not having a bad day, and I'm not angry, I'm just stating my perspective, in the current reality of the project. I'm sorry you didn't like my response....

You want a technical reason? Well, there is none, it's not a technical problem, it's a capacity problem and it's about project governance. Being a non-technical problem doesn't negate its existence, it's about the people behind the code.

> If somebody steps up and creates a PR integrating adrf, would you be willing to accept it?

The problem with accepting such PR a bit like [accepting a puppy](https://snarky.ca/setting-expectations-for-open-source-participation/#:~:text=It%20can%20be%20like%20someone%20trying%20to%20give%20you%20a%20puppy%20you%20didn%27t%20ask%20for%20or%20saying%2C%20%22I%27m%20cleaning%20up%20your%20mess%22.), sure it might be fine on surface but who's going to maintain it for the years to come?

**Comment by alexandernst** [comment]
fair enough 🫡🤝

**Comment by terencehonles** [comment]
> Let me revert this question: what prevetns you/folks from investing their energy into ADRF? What can't be done in ADRF that would justify doing in DRF?

One of the problems with adrf is it has a bus factor of 1, and I don't believe @em1208 has the capacity to maintain the project. I was planning on asking the owner @em1208 about possibly moving the project to the Django Commons org (I would have suggested jazzband, but that looks like it's sunsetting). I have opened 2 relatively minor PRs which fix some deprecation warnings we're seeing and also fix the test configuration since I couldn't test my change.

The problem with this whole discussion was that the response from DRF was effectively: no we don't want to support it / putting it here will require backwards compatibility so someone else will need to do it externally. The PR author who tried to address this issue then volunteered to create the package, but likely never maintained a public package or was offered support on how they might build a community that would allow the package to not just die. I definitely understand the problem of maintenance and triaging and approving PRs, so I'm not downplaying this effort anywhere.

To return to your original question: what can't be done in ADRF is updating base classes without monkey-patching implementations or creating upstream PRs that allow both sync and async support to use a common base. This adds time and effort that is wasted in trying to work with a bandwidth constrained upstream, or potentially brittle support that others will not be factoring in.

What might help is to ask for async volunteers, that will add and maintain async support in DRF. That way the maintenance burden you are suggesting can be shared between more volunteers, and by ones that are specifically interested in async. We are in the process of converting more of our code to async, but the lack of activity in adrf is concerning for us in our adoption and I *really* don't want to have to create a fork and try to maintain another community. I can help support a living and active community, but I do not have the time to start a community from scratch.

Since async support is growing in Django and the Python community in general, I do think it's in the best interest of this package to consider how it plans to add 1st party async support so that people don't just skip over it and use a different framework because of the lack of async support. This package doesn't have a very fast release cadence and it seems beneficial to start now in considering and implementing things.

As my company is going to be using more async code in the future, I can volunteer to help in this front, but I don't know how encode is structured or if it accepts new volunteers. I'll turn the organization question around to you: Does it make sense for django-rest-framework to move to the Django Commons org? Would that allow the DRF project to grow / have more volunteers or does encode have the bandwidth to manage adding new members?

**Comment by browniebroke** [comment]
Thanks for the long and thoughtful response, really appreciated.

> One of the problems with adrf is it has a bus factor of 1

Unfortunately, our bus factor isn't much higher at the moment (maybe 2 or 2.5), and I feel a bit limited while we're under the encode organisation... 

> I'll turn the organization question around to you: Does it make sense for django-rest-framework to move to the Django Commons org? Would that allow the DRF project to grow / have more volunteers or does encode have the bandwidth to manage adding new members?

I'm glad you asked 😄 I've started [the transfer process](github.com/django-commons/membership/issues/188) more than a year ago, but it's a blocked at the moment. I was indeed hoping that being under the commons org would help grow the core team and onboard more people at various levels.

[user hat on]
I'm also a user of DRF and for time to time I also miss having async support, but on the other hand, I'm not 100% sure it would solve many problems on my main the project. I've hit some [issues with pytest-django and asyncio](https://github.com/pytest-dev/pytest-django/issues/580) so I feel like this is not the only blocker...
[user hat off]

**Comment by terencehonles** [comment]
Thanks for the honest response

> I'm glad you asked 😄 I've started [the transfer process](github.com/django-commons/membership/issues/188) more than a year ago, but it's a blocked at the moment.

The transfer link you shared is private, but is there anything we can do to possibly help that along? (including volunteering to support the project or getting any tooling in place)

> [user hat on]
> I'm also a user of DRF and for time to time I also miss having async support, but on the other hand, I'm not 100% sure it would solve many problems on my main the project. I've hit some [issues with pytest-django and asyncio](https://github.com/pytest-dev/pytest-django/issues/580) so I feel like this is not the only blocker...
> [user hat off]

Yeah, I think there will be a lot of things that will continue to evolve, but unblocking async to be used more will allow people to see these problems and then come up with fixes for them.

For us, we've using a very specific configuration and we've worked around the pytest-django issue you linked (we started seeing these issues when using `adrf`), but I do agree this will need to be handled differently if we're expecting it to work for everyone.

**Comment by johnthagen** [comment]
> The transfer link you shared is private

I think @browniebroke simply had a copy/paste issue in his post. Here is the link:

- https://github.com/django-commons/membership/issues/188

**Comment by auvipy** [comment]
we might consider an official extension later, based on the available extensions... I can provide maintenance support for that as well. may be we can do that after the transfer?

**Comment by ShaysFrame** [comment]
2026 and Django's batteries are still not async out of the box... 
Aw, look, we have batteries included, but wait, don't look too deep.
