### ISSUE TITLE
TypeError: 'type' object is not iterable if one item in settings

### ISSUE THREAD

**Issue by folt** [encode/django-rest-framework#8605]
my pyproject.toml
```
python = "^3.10"
djangorestframework = "^3.13.1"
```

my settings
```
REST_FRAMEWORK = {
    ....
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication'
    ),

}
```

with these settings I get an error
```
  File "/py3.10/lib/python3.10/site-packages/rest_framework/views.py", line 272, in get_authenticators
    return [auth() for auth in self.authentication_classes]
TypeError: 'type' object is not iterable
```

When investigating the problem, this is due to an error in loading the settings. There is no comma in `DEFAULT_AUTHENTICATION_CLASSES`, so the variable changes type from tuple to type.

Perhaps it is worth checking the type of settings variables and writing a warning if they have problems?

**Comment by tomchristie** [comment]
It's an easy error to make in Python's syntax, since the difference between a 1-element-tuple and a pair of empty brackets is just a single comma. But no I don't think we'll be adding any extra checking for this. REST framework is pretty much in maintenance mode... track newer Django and Python releases, but otherwise avoid making any more changes to the codebase if at all possible.
