### ISSUE TITLE
I have a error for import 'unicode_to_repr' from compat.

### ISSUE THREAD

**Issue by joyhuchao** [encode/django-rest-framework#8640]
restframework version is 3.13.1
Django version is 4.1..1

I have the error about import 'unicode_to_repr' from compat.
Could you fixed the function.

**Comment by tomchristie** [comment]
That's a private bit of implementation detail that [hasn't needed to exist anymore](https://github.com/encode/django-rest-framework/pull/6615/files#diff-cdecb893483491bdcd9b87ab4a7d24f5ecc8db3f254a8c672eb5c34fb857eee0), [since we dropped Python 2 support](https://www.django-rest-framework.org/community/release-notes/#3100).

Whatever code is calling it is broken.
