### ISSUE TITLE
serializer.JSONField dose not save the decoded data when doing the to_internal_value

### ISSUE THREAD

**Issue by lookfun** [encode/django-rest-framework#9085]
https://github.com/encode/django-rest-framework/blob/40eccb0d6cdb769876dbb79724c5871b4f04163d/rest_framework/fields.py#L1782
json.dumps result dosen't save to 'data'
when this field save to db, the type of the data is a dict, and may save with the wrong format of json (with single quota).

**Comment by auvipy** [comment]
please provide test case aswell

**Comment by sevdog** [comment]
That line does not need to alter the `data` since it just a validation check to ensure that provided data is JSON-serializable.

https://github.com/encode/django-rest-framework/blob/40eccb0d6cdb769876dbb79724c5871b4f04163d/rest_framework/fields.py#L1776-L1785

The method does the following:
1. check if the provided data is to be considered raw data or not
2. if raw data (aka: a string or bytes) decode it
3. otherwhise ensure that it can be dumped in JSON format without raising any error

Line 1782 does the latest check, so if that dump is going to be saved into `data` that would cause an unwanted change.

To give a real example:

```python
from rest_framework.fields import JSONField

field = JSONField()
field.to_internal_value({'hello': 'world'})
>> {'hello': 'world'}
```

**Comment by auvipy** [comment]
So I guess we can close the issue or transfer it to a discussion!

**Comment by lookfun** [comment]
Sorry, jus this problem: [Enabling JSON1 extension on SQLite](https://docs.djangoproject.com/en/5.0/ref/databases/#sqlite-json1).
And because of missing sqlite json extension, my code can not save json data correctly(transfer all the “ to ‘).

**Comment by sevdog** [comment]
This is not a problem of rest-framework rather an issue with the SQLite installation.

If you cannot update SQLite I suggest to use the legacy jsonfield https://github.com/rpkilby/jsonfield/ which should map to a TEXT field on database.

**Comment by lookfun** [comment]
> This is not a problem of rest-framework rather an issue with the SQLite installation.
> 
> If you cannot update SQLite I suggest to use the legacy jsonfield https://github.com/rpkilby/jsonfield/ which should map to a TEXT field on database.
> 
> Note that that repo, nor other regarding custom JSON field implementations, is no more maintained.

I follow the guide and upgrade SQLite, and the problem solved.
