### ISSUE TITLE
from django.utils.translation import ugettext_lazy as _

### ISSUE THREAD

**Issue by mitulparmar7161** [encode/django-rest-framework#9226]
from django.utils.translation import ugettext_lazy as _

getting this error while using any routes of rest framework

**Comment by Ayatade** [comment]
How do you suggest this issue be fixed?

**Comment by mitulparmar7161** [comment]
> How do you suggest this issue be fixed?
from django.utils.translation import ugettext_lazy as _

ugettext_lazy as _ is now changed to gettext_lazy as _
in django-4 i use "rest-auth-dj4" to fix this error and its working fine for me 
but now django-5 is relesed so that "rest-auth-dj4" is not working on this version (django5)

**Comment by ulgens** [comment]
@mitulparmar7161 Which version of the DRF you are using? Without any additional packages, this problem shouldn't exist in the latest version. If you have the latest DRF and Python, but still getting that error with `rest-auth-dj4`, it seems like the problem is in that package.

I tried to check the dependencies of that, thinking it's a package but it doesn't exist on PyPI.

**Comment by mitulparmar7161** [comment]
@ulgens

I was using latest version of Django == 5.0.2 and DRF = 3.14.1 but was still encountering an error due to Django's latest version, when i downgrade Django version to 4.2.1 it started working for me

**Comment by auvipy** [comment]
i think it is not a DRF issue
