### ISSUE TITLE
Camel-case model field names

### ISSUE THREAD

**Issue by jacobg** [encode/django-rest-framework#944]
The convention for Django model field names is to underscore them, while the convention for  Javascript variables is camel-case. It would be great for DRF to automatically convert between the two.

More on this issue in this thread: 
https://groups.google.com/forum/#!searchin/django-rest-framework/camelcase/django-rest-framework/jpb2NNpAMto/tFOt5dD_9NEJ

Tom suggested the following solution in that thread:

   _Something along the lines of a 'get_field_name' on the serializer class that can be overridden, and a setting that defines the default function and allows secs to switch to a different default style._

**Comment by hwkns** [comment]
FWIW, this seems like a common enough use case (I'd guess that JS, Java, and Swift are probably the most popular consumers of DRF endpoints), and the code to implement it is small enough, that it merits being part of the DRF project, rather than a separate dependency (which forces end users to keep up with version matching between dependencies and vetting whether or not the camel case project still works).

Apologies for the comment on a dead issue, but I didn't want to create a new one.

**Comment by yhuanghamu** [comment]
I am surprised that it has been 5 years, and django rest still doesn't support this feature.

**Comment by dakotahawkins** [comment]
@xordoquy It looks like it's infrequently updated and even so contains fixes not published to the package.

**Comment by xordoquy** [comment]
Thanks @dakotahawkins for the clarification.
I still don't think there's enough traction (as the package seems unsupported) to add it to DRF core as opposed to the work it adds.
In my opinion, the solution is simple enough and can be adapted if the existing package doesn't exactly match a project's requirements.

**Comment by carltongibson** [comment]
I don't see why this keeps coming up. _"Use a custom renderer" (and parser too) is the advice. Sure enough that's exactly what the package contains. If it's unmaintained, fork it, merge the PR yourself. (Welcome to Open Source.) There's no enough code there that you can't just pull it into your project wholesale.

**Comment by dakotahawkins** [comment]
@carltongibson 

I'd suggest it comes up because it seems like it would be in the wheelhouse of this project. For my part, I've been working with all of this for a very short time, and in my estimation doing it myself isn't worth the added risk (though I'm no stranger to Open Source, I'm just not really a web developer).

If an available package was maintained/used enough for me to trust them, I'd probably be trying it.

Don't get me wrong, I don't want to sound like I'm making demands or anything. I'm just chiming in to say I _wish_ it were either built-in to DRF or better maintained elsewhere.

**Comment by xordoquy** [comment]
@dakotahawkins it's been a pleasure for me reading your thoughts and discuss with you.
I agree it would be a nice to have feature included with core and I'm sorry to notice that the package for that feature needs more love/work.
However adding more features to DRF core means more overall work and increase the risk of burnout for the maintainers. One of the reason we try to keep the core as lean as possible and resist so much to add things to core itself.

**Comment by dakotahawkins** [comment]
@xordoquy Thank you, and I certainly understand that. At the very least I feel this discussion is helpful to others who (like me) wonder for the first time if anybody else has had the same issue they've had!

It was reassuring and helpful to me to find recent comments on this issue, even if it remains closed forever, so thank you and @carltongibson for checking back in here again :)
